# Generated by Django 5.2.17 on 2026-09-15 10:10
# ruff: noqa: E501

from django.db import migrations, models

import apps.core.db.uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCatalogDaily',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField(db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('tenant_name', models.CharField(max_length=255)),
                ('business_id', models.UUIDField(db_index=True)),
                ('business_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(db_index=True, max_length=80)),
                ('item_kind', models.CharField(choices=[('service', 'Service'), ('sku', 'SKU')], db_index=True, max_length=16)),
                ('item_id', models.UUIDField(db_index=True)),
                ('item_name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('activity_count', models.PositiveIntegerField(default=0)),
                ('units', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('metrics', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'platform_catalog_daily',
                'ordering': ['-day', '-revenue'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'deleted_at'], name='platform_ca_is_acti_7286b3_idx'), models.Index(fields=['created_at'], name='platform_ca_created_60f305_idx'), models.Index(fields=['updated_at'], name='platform_ca_updated_87decc_idx'), models.Index(fields=['day', 'item_kind', 'product_code'], name='platform_ca_day_2df16c_idx'), models.Index(fields=['tenant_id', 'day'], name='platform_ca_tenant__f5963b_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'business_id', 'item_kind', 'item_id'), name='uq_platform_catalog_daily_item')],
            },
        ),
        migrations.CreateModel(
            name='PlatformUsageDaily',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField(db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('tenant_slug', models.SlugField(max_length=120)),
                ('tenant_name', models.CharField(max_length=255)),
                ('business_id', models.UUIDField(db_index=True)),
                ('business_code', models.SlugField(max_length=80)),
                ('business_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(db_index=True, max_length=80)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('bookings', models.PositiveIntegerField(default=0)),
                ('completed_bookings', models.PositiveIntegerField(default=0)),
                ('cancelled_bookings', models.PositiveIntegerField(default=0)),
                ('no_show_bookings', models.PositiveIntegerField(default=0)),
                ('booking_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unique_booking_customers', models.PositiveIntegerField(default=0)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('gmv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('units_sold', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('unique_shop_customers', models.PositiveIntegerField(default=0)),
                ('returns', models.PositiveIntegerField(default=0)),
                ('refund_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('notifications_sent', models.PositiveIntegerField(default=0)),
                ('tickets_opened', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'platform_usage_daily',
                'ordering': ['-day', 'tenant_name', 'business_name', 'product_code'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'deleted_at'], name='platform_us_is_acti_1067f2_idx'), models.Index(fields=['created_at'], name='platform_us_created_64e8b8_idx'), models.Index(fields=['updated_at'], name='platform_us_updated_570680_idx'), models.Index(fields=['day', 'product_code'], name='platform_us_day_17d2c3_idx'), models.Index(fields=['tenant_id', 'day'], name='platform_us_tenant__3ecb00_idx'), models.Index(fields=['business_id', 'day'], name='platform_us_busines_7e02d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'tenant_id', 'business_id', 'product_code'), name='uq_platform_usage_daily_grain')],
            },
        ),
    ]
