# Generated by Django 5.2.15 on 2026-07-04 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.db.uuid
import apps.platform_media.validators.media


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("tenancy", "0003_rename_tenants_slug_f70d36_idx_tenants_slug_899f50_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageProvider",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("local", "Local Storage"),
                            ("s3", "Amazon S3"),
                            ("gcs", "Google Cloud Storage"),
                            ("azure", "Azure Blob Storage"),
                            ("cloudinary", "Cloudinary"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "media_storage_providers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MediaFolder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "folder_type",
                    models.CharField(
                        choices=[
                            ("business", "Business"),
                            ("staff", "Staff"),
                            ("customers", "Customers"),
                            ("services", "Services"),
                            ("documents", "Documents"),
                            ("temp", "Temp"),
                            ("archive", "Archive"),
                        ],
                        db_index=True,
                        default="business",
                        max_length=32,
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_folders",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "media_folders",
                "ordering": ["folder_type", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("pdf", "PDF"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("storage_filename", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("file_extension", models.CharField(db_index=True, max_length=16)),
                ("mime_type", models.CharField(db_index=True, max_length=120)),
                ("file_size", models.PositiveBigIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "storage_provider",
                    models.CharField(
                        choices=[
                            ("local", "Local Storage"),
                            ("s3", "Amazon S3"),
                            ("gcs", "Google Cloud Storage"),
                            ("azure", "Azure Blob Storage"),
                            ("cloudinary", "Cloudinary"),
                        ],
                        db_index=True,
                        default="local",
                        max_length=32,
                    ),
                ),
                ("storage_path", models.CharField(max_length=512)),
                ("checksum", models.CharField(db_index=True, max_length=128)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        db_index=True,
                        default="private",
                        max_length=16,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.platform_media.validators.media.validate_tags],
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="platform_media",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media",
                        to="platform_media.mediafolder",
                    ),
                ),
            ],
            options={
                "db_table": "media",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="mediafolder",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="media_folde_is_acti_036494_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafolder",
            index=models.Index(fields=["created_at"], name="media_folde_created_5a0c74_idx"),
        ),
        migrations.AddIndex(
            model_name="mediafolder",
            index=models.Index(fields=["updated_at"], name="media_folde_updated_de787a_idx"),
        ),
        migrations.AddIndex(
            model_name="mediafolder",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="media_folde_tenant__8e6c3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafolder",
            index=models.Index(
                fields=["tenant", "created_at"], name="media_folde_tenant__2fbc65_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mediafolder",
            constraint=models.UniqueConstraint(
                fields=("tenant", "path"), name="uq_media_folder_tenant_path"
            ),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["is_active", "deleted_at"], name="media_is_acti_0070ed_idx"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["created_at"], name="media_created_3b0875_idx"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["updated_at"], name="media_updated_ab23cb_idx"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="media_tenant__214cae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["tenant", "created_at"], name="media_tenant__75c44a_idx"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(
                fields=["tenant", "business", "media_type"], name="media_tenant__fa521d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(
                fields=["tenant", "folder", "visibility"], name="media_tenant__14670d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["tenant", "checksum"], name="media_tenant__d4f467_idx"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["tenant", "mime_type"], name="media_tenant__28a516_idx"),
        ),
        migrations.AddConstraint(
            model_name="media",
            constraint=models.UniqueConstraint(
                fields=("tenant", "checksum", "storage_provider"),
                name="uq_media_tenant_checksum_provider",
            ),
        ),
    ]
