from django.urls import path

from apps.platform_admin.api import (
    PlatformAddonPricingView,
    PlatformAnnouncementPublicView,
    PlatformAnnouncementsView,
    PlatformAuditFeedView,
    PlatformCouponsView,
    PlatformCreateTenantView,
    PlatformCreditsView,
    PlatformExportView,
    PlatformHelpArticlesAdminView,
    PlatformHelpPublicView,
    PlatformImpersonateView,
    PlatformImpersonationEndView,
    PlatformPaymentRefundView,
    PlatformPlanPackagesView,
    PlatformPurgeTenantView,
    PlatformUpiClaimActionView,
    PlatformUpiClaimsView,
    PlatformTenantActionView,
    PlatformTenantBillingActionView,
    PlatformTenantBillingView,
    PlatformTenantFlagsView,
    PlatformTenantPaymentsView,
    PlatformTenantUsersView,
    PlatformTicketDetailView,
    PlatformTicketNoteView,
    PlatformTicketsView,
    PlatformTransferOwnershipView,
    PlatformUserActionView,
    PlatformUserSearchView,
    PlatformInvoicePdfView,
    SupportTicketsView,
)

urlpatterns = [
    path("platform/tenants/create", PlatformCreateTenantView.as_view(), name="platform-tenant-create"),
    path(
        "platform/tenants/<uuid:tenant_id>/actions/<slug:action>",
        PlatformTenantActionView.as_view(),
        name="platform-tenant-action",
    ),
    path(
        "platform/tenants/<uuid:tenant_id>/billing",
        PlatformTenantBillingView.as_view(),
        name="platform-tenant-billing",
    ),
    path(
        "platform/tenants/<uuid:tenant_id>/billing/actions",
        PlatformTenantBillingActionView.as_view(),
        name="platform-tenant-billing-action",
    ),
    path(
        "platform/tenants/<uuid:tenant_id>/users",
        PlatformTenantUsersView.as_view(),
        name="platform-tenant-users",
    ),
    path(
        "platform/tenants/<uuid:tenant_id>/flags",
        PlatformTenantFlagsView.as_view(),
        name="platform-tenant-flags",
    ),
    path(
        "platform/tenants/<uuid:tenant_id>/payments",
        PlatformTenantPaymentsView.as_view(),
        name="platform-tenant-payments",
    ),
    path(
        "platform/tenants/<uuid:tenant_id>/payments/<uuid:payment_id>/refund",
        PlatformPaymentRefundView.as_view(),
        name="platform-payment-refund",
    ),
    path(
        "platform/tenants/<uuid:tenant_id>/payments/<uuid:payment_id>/confirm",
        PlatformUpiClaimActionView.as_view(),
        name="platform-payment-confirm",
    ),
    path(
        "platform/tenants/<uuid:tenant_id>/credits",
        PlatformCreditsView.as_view(),
        name="platform-tenant-credits",
    ),
    path(
        "platform/tenants/<uuid:tenant_id>/impersonate",
        PlatformImpersonateView.as_view(),
        name="platform-tenant-impersonate",
    ),
    path(
        "platform/tenants/<uuid:tenant_id>/transfer-ownership",
        PlatformTransferOwnershipView.as_view(),
        name="platform-tenant-transfer",
    ),
    path(
        "platform/tenants/<uuid:tenant_id>/purge",
        PlatformPurgeTenantView.as_view(),
        name="platform-tenant-purge",
    ),
    path(
        "platform/invoices/<uuid:invoice_id>/pdf",
        PlatformInvoicePdfView.as_view(),
        name="platform-invoice-pdf",
    ),
    path("platform/users/search", PlatformUserSearchView.as_view(), name="platform-user-search"),
    path(
        "platform/users/<uuid:user_id>/actions/<slug:action>",
        PlatformUserActionView.as_view(),
        name="platform-user-action",
    ),
    path("platform/impersonation/end", PlatformImpersonationEndView.as_view(), name="platform-impersonation-end"),
    path(
        "platform/upi-claims",
        PlatformUpiClaimsView.as_view(),
        name="platform-upi-claims",
    ),
    path("platform/coupons", PlatformCouponsView.as_view(), name="platform-coupons"),
    path("platform/plan-packages", PlatformPlanPackagesView.as_view(), name="platform-plan-packages"),
    path(
        "platform/addon-pricing",
        PlatformAddonPricingView.as_view(),
        name="platform-addon-pricing",
    ),
    path("platform/audit", PlatformAuditFeedView.as_view(), name="platform-audit-feed"),
    path("platform/tickets", PlatformTicketsView.as_view(), name="platform-tickets"),
    path(
        "platform/tickets/<uuid:ticket_id>/notes",
        PlatformTicketNoteView.as_view(),
        name="platform-ticket-notes",
    ),
    path(
        "platform/tickets/<uuid:ticket_id>",
        PlatformTicketDetailView.as_view(),
        name="platform-ticket-detail",
    ),
    path("platform/announcements", PlatformAnnouncementsView.as_view(), name="platform-announcements"),
    path(
        "platform/announcements/active",
        PlatformAnnouncementPublicView.as_view(),
        name="platform-announcements-active",
    ),
    path("platform/help/articles", PlatformHelpArticlesAdminView.as_view(), name="platform-help-admin"),
    path("help/articles", PlatformHelpPublicView.as_view(), name="help-articles-public"),
    path("support/tickets", SupportTicketsView.as_view(), name="support-tickets"),
    path("platform/exports/<slug:export_type>", PlatformExportView.as_view(), name="platform-exports"),
]
