# Generated by Django 5.2.17 on 2026-09-24 06:14

import apps.core.db.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0017_businesssettings_whatsapp_integration'),
        ('tenancy', '0004_expand_asset_url_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_messages', to='businesses.business')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'assistant_messages',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssistantThread',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_threads', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_threads', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'assistant_threads',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssistantProposedAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(db_index=True, max_length=80)),
                ('summary', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_proposed_actions', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_proposed_actions', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_actions', to='assistant.assistantmessage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_actions', to='assistant.assistantthread')),
            ],
            options={
                'db_table': 'assistant_proposed_actions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantthread'),
        ),
        migrations.CreateModel(
            name='AssistantUsageDaily',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('usage_date', models.DateField(db_index=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('confirm_count', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_usage_daily', to='businesses.business')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'assistant_usage_daily',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='assistantthread',
            index=models.Index(fields=['is_active', 'deleted_at'], name='assistant_t_is_acti_0a167b_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantthread',
            index=models.Index(fields=['created_at'], name='assistant_t_created_1ffa85_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantthread',
            index=models.Index(fields=['updated_at'], name='assistant_t_updated_9aacd9_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantthread',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='assistant_t_tenant__dfce17_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantthread',
            index=models.Index(fields=['tenant', 'created_at'], name='assistant_t_tenant__f8a0bd_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantthread',
            index=models.Index(fields=['tenant', 'business', 'updated_at'], name='assistant_t_tenant__0662d4_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantproposedaction',
            index=models.Index(fields=['is_active', 'deleted_at'], name='assistant_p_is_acti_45716e_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantproposedaction',
            index=models.Index(fields=['created_at'], name='assistant_p_created_bd4bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantproposedaction',
            index=models.Index(fields=['updated_at'], name='assistant_p_updated_8493e9_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantproposedaction',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='assistant_p_tenant__111cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantproposedaction',
            index=models.Index(fields=['tenant', 'created_at'], name='assistant_p_tenant__2a18fa_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantproposedaction',
            index=models.Index(fields=['tenant', 'business', 'status'], name='assistant_p_tenant__7b5e72_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['is_active', 'deleted_at'], name='assistant_m_is_acti_a5fa0c_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['created_at'], name='assistant_m_created_1eba98_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['updated_at'], name='assistant_m_updated_3c4796_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='assistant_m_tenant__1353ea_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['tenant', 'created_at'], name='assistant_m_tenant__bbddfd_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['tenant', 'thread', 'created_at'], name='assistant_m_tenant__17ec5e_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantusagedaily',
            index=models.Index(fields=['is_active', 'deleted_at'], name='assistant_u_is_acti_ceb3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantusagedaily',
            index=models.Index(fields=['created_at'], name='assistant_u_created_aa35d6_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantusagedaily',
            index=models.Index(fields=['updated_at'], name='assistant_u_updated_638218_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantusagedaily',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='assistant_u_tenant__8d88db_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantusagedaily',
            index=models.Index(fields=['tenant', 'created_at'], name='assistant_u_tenant__db2274_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantusagedaily',
            index=models.Index(fields=['tenant', 'business', 'usage_date'], name='assistant_u_tenant__2b0cd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='assistantusagedaily',
            constraint=models.UniqueConstraint(fields=('tenant', 'business', 'usage_date'), name='uq_assistant_usage_daily_business_date'),
        ),
    ]
