# Generated by Django 5.2.17 on 2026-09-24 09:07

import apps.core.db.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial_assistant'),
        ('businesses', '0017_businesssettings_whatsapp_integration'),
        ('tenancy', '0004_expand_asset_url_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantWallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('balance_paise', models.IntegerField(default=0)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_wallet', to='businesses.business')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'assistant_wallets',
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'deleted_at'], name='assistant_w_is_acti_f3669e_idx'), models.Index(fields=['created_at'], name='assistant_w_created_4bf193_idx'), models.Index(fields=['updated_at'], name='assistant_w_updated_a5609f_idx'), models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='assistant_w_tenant__81ba7a_idx'), models.Index(fields=['tenant', 'created_at'], name='assistant_w_tenant__f81369_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssistantWalletLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, db_index=True, max_length=64)),
                ('charged_paise', models.IntegerField(default=0)),
                ('balance_after_paise', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_wallet_ledger', to='businesses.business')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'assistant_wallet_ledger',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'deleted_at'], name='assistant_w_is_acti_4834fc_idx'), models.Index(fields=['created_at'], name='assistant_w_created_dc8c0b_idx'), models.Index(fields=['updated_at'], name='assistant_w_updated_a50a29_idx'), models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='assistant_w_tenant__2e0a87_idx'), models.Index(fields=['tenant', 'created_at'], name='assistant_w_tenant__d85547_idx'), models.Index(fields=['tenant', 'business', 'created_at'], name='assistant_w_tenant__ad0d3d_idx')],
            },
        ),
    ]
