# Generated by Django 5.2.15 on 2026-07-05 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.db.uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("platform_media", "0001_initial"),
        ("tenancy", "0003_rename_tenants_slug_f70d36_idx_tenants_slug_899f50_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_number", models.CharField(db_index=True, max_length=32, unique=True)),
                ("customer_id", models.UUIDField(db_index=True)),
                ("staff_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("service_id", models.UUIDField(db_index=True)),
                ("appointment_date", models.DateField(db_index=True)),
                ("start_at", models.DateTimeField(db_index=True)),
                ("end_at", models.DateTimeField(db_index=True)),
                ("duration_minutes", models.PositiveIntegerField()),
                ("buffer_before_minutes", models.PositiveIntegerField(default=0)),
                ("buffer_after_minutes", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                            ("no_show", "No Show"),
                            ("expired", "Expired"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("customer_app", "Customer App"),
                            ("operations_dashboard", "Operations Dashboard"),
                            ("platform_admin", "Platform Admin"),
                            ("api", "API"),
                        ],
                        default="customer_app",
                        max_length=40,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("mobile", "Mobile"),
                            ("phone", "Phone"),
                            ("walk_in", "Walk In"),
                            ("api", "API"),
                        ],
                        default="web",
                        max_length=40,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("reschedule_reason", models.TextField(blank=True)),
                (
                    "recurrence_frequency",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom"),
                        ],
                        default="none",
                        max_length=24,
                    ),
                ),
                ("recurrence_rule", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "ordering": ["-start_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BookingAttachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=160)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="bookings.booking",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_attachments",
                        to="platform_media.media",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "booking_attachments",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BookingEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=120)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="bookings.booking",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "booking_events",
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BookingHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=32)),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                            ("no_show", "No Show"),
                            ("expired", "Expired"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="bookings.booking",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "booking_history",
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BookingNote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField()),
                ("is_internal", models.BooleanField(default=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_notes",
                        to="bookings.booking",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "booking_notes",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BookingTimeline",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                            ("no_show", "No Show"),
                            ("expired", "Expired"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="bookings.booking",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "booking_timeline",
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BusinessHoliday",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("date", models.DateField(db_index=True)),
                ("all_day", models.BooleanField(default=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "business_holidays",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BusinessSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("seasonal", "Seasonal"),
                            ("temporary", "Temporary"),
                        ],
                        default="default",
                        max_length=32,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "business_schedules",
                "ordering": ["business", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BusinessWeeklySchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField(db_index=True)),
                ("is_open", models.BooleanField(default=True)),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("break_periods", models.JSONField(blank=True, default=list)),
                ("capacity", models.PositiveIntegerField(default=1)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_schedules",
                        to="businesses.business",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_days",
                        to="bookings.businessschedule",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "business_weekly_schedules",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmergencyClosure",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField(db_index=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_closures",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "emergency_closures",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpecialWorkingDay",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("break_periods", models.JSONField(blank=True, default=list)),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("reason", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_working_days",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "special_working_days",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StaffLeave",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("staff_id", models.UUIDField(db_index=True)),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField(db_index=True)),
                ("leave_type", models.CharField(default="leave", max_length=80)),
                ("reason", models.TextField(blank=True)),
                ("approved", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_leaves",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "staff_leaves",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StaffSpecialAvailability",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("staff_id", models.UUIDField(db_index=True)),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField(db_index=True)),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("reason", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_special_availability",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "staff_special_availability",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StaffWeeklySchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("staff_id", models.UUIDField(db_index=True)),
                ("weekday", models.PositiveSmallIntegerField(db_index=True)),
                ("is_available", models.BooleanField(default=True)),
                ("shift_start", models.TimeField()),
                ("shift_end", models.TimeField()),
                ("break_periods", models.JSONField(blank=True, default=list)),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("overtime_allowed", models.BooleanField(default=False)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_weekly_schedules",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "staff_weekly_schedules",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="bookings_is_acti_2fc20d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["created_at"], name="bookings_created_118d3e_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["updated_at"], name="bookings_updated_199695_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="bookings_tenant__6d0fbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["tenant", "created_at"], name="bookings_tenant__f94044_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["tenant", "business", "appointment_date"],
                name="bookings_tenant__92ce04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["tenant", "staff_id", "start_at", "end_at"],
                name="bookings_tenant__23c4ae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["tenant", "customer_id", "start_at"], name="bookings_tenant__4ce4f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["tenant", "service_id", "start_at"], name="bookings_tenant__d823fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["tenant", "status", "appointment_date"], name="bookings_tenant__8ba953_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingattachment",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="booking_att_is_acti_2b218a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingattachment",
            index=models.Index(fields=["created_at"], name="booking_att_created_c9819e_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingattachment",
            index=models.Index(fields=["updated_at"], name="booking_att_updated_748351_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingattachment",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="booking_att_tenant__0f018b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingattachment",
            index=models.Index(
                fields=["tenant", "created_at"], name="booking_att_tenant__ca8c13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="booking_eve_is_acti_05d581_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=models.Index(fields=["created_at"], name="booking_eve_created_9f3d57_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=models.Index(fields=["updated_at"], name="booking_eve_updated_63f92c_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="booking_eve_tenant__80e202_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=models.Index(
                fields=["tenant", "created_at"], name="booking_eve_tenant__bac20f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookinghistory",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="booking_his_is_acti_aa6d85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookinghistory",
            index=models.Index(fields=["created_at"], name="booking_his_created_948e7f_idx"),
        ),
        migrations.AddIndex(
            model_name="bookinghistory",
            index=models.Index(fields=["updated_at"], name="booking_his_updated_c4ab2e_idx"),
        ),
        migrations.AddIndex(
            model_name="bookinghistory",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="booking_his_tenant__13f4f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookinghistory",
            index=models.Index(
                fields=["tenant", "created_at"], name="booking_his_tenant__c6ef0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingnote",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="booking_not_is_acti_52fce5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingnote",
            index=models.Index(fields=["created_at"], name="booking_not_created_d64f2d_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingnote",
            index=models.Index(fields=["updated_at"], name="booking_not_updated_f0f388_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingnote",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="booking_not_tenant__42b82a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingnote",
            index=models.Index(
                fields=["tenant", "created_at"], name="booking_not_tenant__a19814_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingtimeline",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="booking_tim_is_acti_b3117f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingtimeline",
            index=models.Index(fields=["created_at"], name="booking_tim_created_2e46b0_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingtimeline",
            index=models.Index(fields=["updated_at"], name="booking_tim_updated_4998d3_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingtimeline",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="booking_tim_tenant__f6e762_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingtimeline",
            index=models.Index(
                fields=["tenant", "created_at"], name="booking_tim_tenant__fcb802_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessholiday",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="business_ho_is_acti_6fefd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessholiday",
            index=models.Index(fields=["created_at"], name="business_ho_created_fa0733_idx"),
        ),
        migrations.AddIndex(
            model_name="businessholiday",
            index=models.Index(fields=["updated_at"], name="business_ho_updated_c20338_idx"),
        ),
        migrations.AddIndex(
            model_name="businessholiday",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="business_ho_tenant__e0dfba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessholiday",
            index=models.Index(
                fields=["tenant", "created_at"], name="business_ho_tenant__668273_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessholiday",
            index=models.Index(
                fields=["tenant", "business", "date"], name="business_ho_tenant__4492fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessschedule",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="business_sc_is_acti_88a453_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessschedule",
            index=models.Index(fields=["created_at"], name="business_sc_created_1925cf_idx"),
        ),
        migrations.AddIndex(
            model_name="businessschedule",
            index=models.Index(fields=["updated_at"], name="business_sc_updated_858caa_idx"),
        ),
        migrations.AddIndex(
            model_name="businessschedule",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="business_sc_tenant__f51a6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessschedule",
            index=models.Index(
                fields=["tenant", "created_at"], name="business_sc_tenant__dd2c46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessweeklyschedule",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="business_we_is_acti_574a03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessweeklyschedule",
            index=models.Index(fields=["created_at"], name="business_we_created_5a09b1_idx"),
        ),
        migrations.AddIndex(
            model_name="businessweeklyschedule",
            index=models.Index(fields=["updated_at"], name="business_we_updated_9ac142_idx"),
        ),
        migrations.AddIndex(
            model_name="businessweeklyschedule",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="business_we_tenant__8f9e60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessweeklyschedule",
            index=models.Index(
                fields=["tenant", "created_at"], name="business_we_tenant__f02237_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="businessweeklyschedule",
            constraint=models.UniqueConstraint(
                fields=("schedule", "weekday"), name="uq_business_schedule_weekday"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyclosure",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="emergency_c_is_acti_59ae1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyclosure",
            index=models.Index(fields=["created_at"], name="emergency_c_created_0eccad_idx"),
        ),
        migrations.AddIndex(
            model_name="emergencyclosure",
            index=models.Index(fields=["updated_at"], name="emergency_c_updated_154de0_idx"),
        ),
        migrations.AddIndex(
            model_name="emergencyclosure",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="emergency_c_tenant__84a1b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyclosure",
            index=models.Index(
                fields=["tenant", "created_at"], name="emergency_c_tenant__0f9f12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specialworkingday",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="special_wor_is_acti_2651bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specialworkingday",
            index=models.Index(fields=["created_at"], name="special_wor_created_48c5a8_idx"),
        ),
        migrations.AddIndex(
            model_name="specialworkingday",
            index=models.Index(fields=["updated_at"], name="special_wor_updated_6d6468_idx"),
        ),
        migrations.AddIndex(
            model_name="specialworkingday",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="special_wor_tenant__2309ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specialworkingday",
            index=models.Index(
                fields=["tenant", "created_at"], name="special_wor_tenant__081cef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffleave",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="staff_leave_is_acti_358c57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffleave",
            index=models.Index(fields=["created_at"], name="staff_leave_created_98d26b_idx"),
        ),
        migrations.AddIndex(
            model_name="staffleave",
            index=models.Index(fields=["updated_at"], name="staff_leave_updated_da40f1_idx"),
        ),
        migrations.AddIndex(
            model_name="staffleave",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="staff_leave_tenant__348dab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffleave",
            index=models.Index(
                fields=["tenant", "created_at"], name="staff_leave_tenant__7e2620_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffspecialavailability",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="staff_speci_is_acti_116bda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffspecialavailability",
            index=models.Index(fields=["created_at"], name="staff_speci_created_a59d25_idx"),
        ),
        migrations.AddIndex(
            model_name="staffspecialavailability",
            index=models.Index(fields=["updated_at"], name="staff_speci_updated_a79885_idx"),
        ),
        migrations.AddIndex(
            model_name="staffspecialavailability",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="staff_speci_tenant__454a2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffspecialavailability",
            index=models.Index(
                fields=["tenant", "created_at"], name="staff_speci_tenant__57fdb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffweeklyschedule",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="staff_weekl_is_acti_1ed37c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffweeklyschedule",
            index=models.Index(fields=["created_at"], name="staff_weekl_created_dcb679_idx"),
        ),
        migrations.AddIndex(
            model_name="staffweeklyschedule",
            index=models.Index(fields=["updated_at"], name="staff_weekl_updated_bce9fb_idx"),
        ),
        migrations.AddIndex(
            model_name="staffweeklyschedule",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="staff_weekl_tenant__93c90b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffweeklyschedule",
            index=models.Index(
                fields=["tenant", "created_at"], name="staff_weekl_tenant__16aa83_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffweeklyschedule",
            constraint=models.UniqueConstraint(
                fields=("tenant", "business", "staff_id", "weekday"),
                name="uq_staff_weekly_schedule",
            ),
        ),
    ]
