# Generated by Django 5.2.16 on 2026-07-26 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_mobile_customer_features"),
        ("businesses", "0010_plan_entitlements_offices_booking_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="businesses.branch",
            ),
        ),
    ]
