# Generated by Django 5.2.17 on 2026-08-15 17:54

import apps.core.db.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_plan_entitlements_offices_booking_branch"),
        ("businesses", "0016_remove_crmie_invoiceie"),
        ("tenancy", "0004_expand_asset_url_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffEmergencySlot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("staff_id", models.UUIDField(db_index=True)),
                ("date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("reason", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_emergency_slots",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "staff_emergency_slots",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="staff_emerg_is_acti_7420eb_idx"
                    ),
                    models.Index(fields=["created_at"], name="staff_emerg_created_9ade77_idx"),
                    models.Index(fields=["updated_at"], name="staff_emerg_updated_2fcab1_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="staff_emerg_tenant__171285_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="staff_emerg_tenant__c809b0_idx"
                    ),
                    models.Index(
                        fields=["tenant", "business", "staff_id", "date"],
                        name="staff_emerg_tenant__3778f1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffSlotBlock",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("staff_id", models.UUIDField(db_index=True)),
                ("date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("reason", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_slot_blocks",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "staff_slot_blocks",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="staff_slot__is_acti_59bb73_idx"
                    ),
                    models.Index(fields=["created_at"], name="staff_slot__created_8fb752_idx"),
                    models.Index(fields=["updated_at"], name="staff_slot__updated_a46979_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="staff_slot__tenant__9321ef_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="staff_slot__tenant__6034fb_idx"
                    ),
                    models.Index(
                        fields=["tenant", "business", "staff_id", "date"],
                        name="staff_slot__tenant__37bce7_idx",
                    ),
                ],
            },
        ),
    ]
