# Generated by Django 5.2.17 on 2026-09-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_line_items'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookinglineitem',
            new_name='booking_lin_is_acti_6c029b_idx',
            old_name='booking_lin_is_acti_4f2c11_idx',
        ),
        migrations.RenameIndex(
            model_name='bookinglineitem',
            new_name='booking_lin_created_f33898_idx',
            old_name='booking_lin_created_8e9f22_idx',
        ),
        migrations.RenameIndex(
            model_name='bookinglineitem',
            new_name='booking_lin_updated_05eeff_idx',
            old_name='booking_lin_updated_1a3b44_idx',
        ),
        migrations.RenameIndex(
            model_name='bookinglineitem',
            new_name='booking_lin_tenant__6a2a16_idx',
            old_name='booking_lin_tenant__5c6d77_idx',
        ),
        migrations.RenameIndex(
            model_name='bookinglineitem',
            new_name='booking_lin_tenant__4bc508_idx',
            old_name='booking_lin_tenant__7e8f99_idx',
        ),
        migrations.RenameIndex(
            model_name='bookinglineitem',
            new_name='booking_lin_tenant__3ba9ff_idx',
            old_name='booking_lin_tenant__aa11bb_idx',
        ),
        migrations.RenameIndex(
            model_name='bookinglineitem',
            new_name='booking_lin_tenant__8632a1_idx',
            old_name='booking_lin_tenant__cc22dd_idx',
        ),
        migrations.RenameIndex(
            model_name='bookinglineitem',
            new_name='booking_lin_tenant__189c10_idx',
            old_name='booking_lin_tenant__ee33ff_idx',
        ),
    ]
