from django.db import migrations, models
import django.db.models.deletion


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        ("bookings", "0001_initial"),
        ("businesses", "0001_initial"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("code", models.SlugField(max_length=120)),
                ("name", models.CharField(max_length=160)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("channel", models.CharField(max_length=32)),
                ("locale", models.CharField(default="en", max_length=16)),
                ("variables", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notification_templates", to="businesses.business")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="notifications_notificationtemplate_records", to="tenancy.tenant")),
            ],
            options={"db_table": "notification_templates"},
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("channel", models.CharField(max_length=32)),
                ("is_enabled", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="notifications_notificationpreference_records", to="tenancy.tenant")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notification_preferences", to="authentication.user")),
            ],
            options={"db_table": "notification_preferences"},
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("channel", models.CharField(max_length=32)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("status", models.CharField(db_index=True, default="pending", max_length=32)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("booking", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications", to="bookings.booking")),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="businesses.business")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="notifications_notification_records", to="tenancy.tenant")),
                ("template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications", to="notifications.notificationtemplate")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications", to="authentication.user")),
            ],
            options={"db_table": "notifications", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="NotificationQueue",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("notification", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="queue_entries", to="notifications.notification")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="notifications_notificationqueue_records", to="tenancy.tenant")),
            ],
            options={"db_table": "notification_queue"},
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("provider", models.CharField(blank=True, max_length=80)),
                ("response_code", models.CharField(blank=True, max_length=80)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("notification", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="notifications.notification")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="notifications_notificationlog_records", to="tenancy.tenant")),
            ],
            options={"db_table": "notification_logs"},
        ),
        migrations.CreateModel(
            name="NotificationHistory",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("event_type", models.CharField(max_length=120)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("notification", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="history", to="notifications.notification")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="notifications_notificationhistory_records", to="tenancy.tenant")),
            ],
            options={"db_table": "notification_history"},
        ),
        migrations.RunPython(noop, migrations.RunPython.noop),
    ]
