# Generated by Django 5.2.16 on 2026-07-25 09:10

import apps.core.db.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("tenancy", "0004_expand_asset_url_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileDevice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expo_push_token", models.CharField(db_index=True, max_length=255)),
                ("platform", models.CharField(blank=True, max_length=32)),
                ("app_flavor", models.CharField(blank=True, max_length=120)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mobile_devices",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="mobiledevice",
            index=models.Index(fields=["is_active", "deleted_at"], name="mobile_devi_is_acti_624933_idx"),
        ),
        migrations.AddIndex(
            model_name="mobiledevice",
            index=models.Index(fields=["created_at"], name="mobile_devi_created_01f80b_idx"),
        ),
        migrations.AddIndex(
            model_name="mobiledevice",
            index=models.Index(fields=["updated_at"], name="mobile_devi_updated_8bb2ca_idx"),
        ),
        migrations.AddIndex(
            model_name="mobiledevice",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"],
                name="mobile_devi_tenant__85f0f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mobiledevice",
            index=models.Index(fields=["tenant", "created_at"], name="mobile_devi_tenant__422df8_idx"),
        ),
        migrations.AddConstraint(
            model_name="mobiledevice",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user", "expo_push_token"),
                name="uq_mobile_device_tenant_user_token",
            ),
        ),
    ]
