# Generated by Django 5.2.17 on 2026-09-01 19:43

import apps.core.db.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_rename_booking_lin_is_acti_4f2c11_idx_booking_lin_is_acti_6c029b_idx_and_more'),
        ('businesses', '0016_remove_crmie_invoiceie'),
        ('notifications', '0002_mobile_customer_features'),
        ('tenancy', '0004_expand_asset_url_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('firebase_push', 'Firebase Push'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='id',
            field=models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='id',
            field=models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('firebase_push', 'Firebase Push'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='id',
            field=models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='id',
            field=models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('firebase_push', 'Firebase Push'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='id',
            field=models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_active', 'deleted_at'], name='notificatio_is_acti_a84cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['updated_at'], name='notificatio_updated_488e78_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='notificatio_tenant__6a979b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'created_at'], name='notificatio_tenant__f87df4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['is_active', 'deleted_at'], name='notificatio_is_acti_762066_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['created_at'], name='notificatio_created_307e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['updated_at'], name='notificatio_updated_7dff95_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='notificatio_tenant__98fd99_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['tenant', 'created_at'], name='notificatio_tenant__27faa1_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['is_active', 'deleted_at'], name='notificatio_is_acti_4b3c28_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at'], name='notificatio_created_45a1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['updated_at'], name='notificatio_updated_de54df_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='notificatio_tenant__48c797_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['tenant', 'created_at'], name='notificatio_tenant__e2f80e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['is_active', 'deleted_at'], name='notificatio_is_acti_5847c4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['created_at'], name='notificatio_created_ad941a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['updated_at'], name='notificatio_updated_eac94d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='notificatio_tenant__879611_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['tenant', 'created_at'], name='notificatio_tenant__aabd75_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['is_active', 'deleted_at'], name='notificatio_is_acti_c82370_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['created_at'], name='notificatio_created_28f81e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['updated_at'], name='notificatio_updated_efbf66_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='notificatio_tenant__294ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['tenant', 'created_at'], name='notificatio_tenant__35082b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['is_active', 'deleted_at'], name='notificatio_is_acti_894ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['created_at'], name='notificatio_created_375143_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['updated_at'], name='notificatio_updated_563809_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='notificatio_tenant__f4ffcb_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['tenant', 'created_at'], name='notificatio_tenant__e9df61_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('tenant', 'user', 'channel'), name='uq_notification_preference_tenant_user_channel'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'business', 'code', 'locale'), name='uq_notification_template_tenant_business_code_locale'),
        ),
    ]
