# Generated by Django 5.2.17 on 2026-08-15 17:54

import apps.core.db.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin", "0005_addon_pricing"),
        ("tenancy", "0004_expand_asset_url_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAffiliate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "affiliate_type",
                    models.CharField(
                        choices=[("tenant", "Tenant"), ("partner", "Partner")],
                        db_index=True,
                        default="partner",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("disabled", "Disabled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_affiliates",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "platform_affiliates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlatformAffiliateCode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="platform_admin.platformaffiliate",
                    ),
                ),
            ],
            options={
                "db_table": "platform_affiliate_codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PlatformReferral",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("months", models.PositiveSmallIntegerField(default=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("expired", "Expired"), ("void", "Void")],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="platform_admin.platformaffiliate",
                    ),
                ),
                (
                    "affiliate_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="platform_admin.platformaffiliatecode",
                    ),
                ),
                (
                    "referred_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_referrals_received",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "platform_referrals",
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformReferralAccrual",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_yyyy_mm", models.CharField(db_index=True, max_length=7)),
                ("amount_paise", models.PositiveIntegerField()),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("payout", "Payout")],
                        default="credit",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("credited", "Credited"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accruals",
                        to="platform_admin.platformreferral",
                    ),
                ),
            ],
            options={
                "db_table": "platform_referral_accruals",
                "ordering": ["-period_yyyy_mm", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformPayout",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_paise", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("paid", "Paid"), ("void", "Void")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("payment_ref", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="platform_admin.platformaffiliate",
                    ),
                ),
                (
                    "accrual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payouts",
                        to="platform_admin.platformreferralaccrual",
                    ),
                ),
            ],
            options={
                "db_table": "platform_payouts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="platformreferral",
            constraint=models.UniqueConstraint(
                fields=("referred_tenant",), name="uq_platform_referral_referred_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="platformreferralaccrual",
            constraint=models.UniqueConstraint(
                fields=("referral", "period_yyyy_mm"), name="uq_platform_referral_accrual_period"
            ),
        ),
    ]
