# Generated by Django 5.2.17 on 2026-08-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin", "0011_affiliate_ledger"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="platformaffiliateledgerentry",
            new_name="platform_af_affilia_21cebe_idx",
            old_name="platform_af_affilia_8f1c3a_idx",
        ),
        migrations.RenameIndex(
            model_name="platformaffiliateledgerentry",
            new_name="platform_af_referra_c5539b_idx",
            old_name="platform_af_referra_4b9e2d_idx",
        ),
    ]
