# Generated by Django 5.2.17 on 2026-09-24 09:07

import apps.core.db.uuid
from django.db import migrations, models


def seed_assistant_settings(apps, schema_editor):
    PlatformAssistantSettings = apps.get_model("platform_admin", "PlatformAssistantSettings")
    PlatformAssistantSettings.objects.get_or_create(
        key="default",
        defaults={
            "enabled": True,
            "message_price_paise": 50,
            "confirm_price_paise": 100,
            "suggested_top_up_paise": [5000, 10000, 25000, 50000],
        },
    )


def unseed_assistant_settings(apps, schema_editor):
    PlatformAssistantSettings = apps.get_model("platform_admin", "PlatformAssistantSettings")
    PlatformAssistantSettings.objects.filter(key="default").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin", "0027_backfill_smart_lookup_feature"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAssistantSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(default="default", max_length=20, unique=True)),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When off, free daily limits still apply but prepaid overage is disabled.",
                    ),
                ),
                (
                    "message_price_paise",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Wallet debit per assistant message after free daily messages are used (paise).",
                    ),
                ),
                (
                    "confirm_price_paise",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Wallet debit per confirm after free daily confirms are used (paise).",
                    ),
                ),
                (
                    "suggested_top_up_paise",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Suggested wallet top-up amounts in paise shown to business owners.",
                    ),
                ),
            ],
            options={
                "db_table": "platform_assistant_settings",
            },
        ),
        migrations.RunPython(seed_assistant_settings, unseed_assistant_settings),
    ]
