# Generated by Django 5.2.15 on 2026-07-05 05:39

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models

import apps.core.db.uuid
import apps.services.validators.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("platform_media", "0001_initial"),
        ("tenancy", "0003_rename_tenants_slug_f70d36_idx_tenants_slug_899f50_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_categories",
                        to="businesses.business",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="services.servicecategory",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "service_categories",
                "ordering": ["display_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service_code", models.SlugField(max_length=80)),
                ("name", models.CharField(max_length=160)),
                ("display_name", models.CharField(max_length=160)),
                ("short_description", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("hidden", "Hidden"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=32,
                    ),
                ),
                ("online_booking_enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "gender_restriction",
                    models.CharField(
                        choices=[
                            ("any", "Any"),
                            ("female", "Female"),
                            ("male", "Male"),
                            ("custom", "Custom"),
                        ],
                        default="any",
                        max_length=32,
                    ),
                ),
                ("min_age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_age", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.services.validators.services.validate_tags],
                    ),
                ),
                ("display_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("addons_metadata", models.JSONField(blank=True, default=dict)),
                ("packages_metadata", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "db_table": "services",
                "ordering": ["display_order", "display_name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=160)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_images",
                        to="platform_media.media",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="services.service",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "service_images",
                "ordering": ["display_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("color", models.CharField(blank=True, max_length=16)),
                ("description", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_tags",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "service_tags",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceVariant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("sku", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="services.service",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "service_variants",
                "ordering": ["display_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServicePricing",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "sale_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("tax_inclusive", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="services.service",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="services.servicevariant",
                    ),
                ),
            ],
            options={
                "db_table": "service_pricing",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceDuration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("buffer_before_minutes", models.PositiveIntegerField(default=0)),
                ("buffer_after_minutes", models.PositiveIntegerField(default=0)),
                ("cleanup_minutes", models.PositiveIntegerField(default=0)),
                ("is_default", models.BooleanField(default=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="durations",
                        to="services.service",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="durations",
                        to="services.servicevariant",
                    ),
                ),
            ],
            options={
                "db_table": "service_durations",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaxConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tax_name", models.CharField(max_length=80)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=3, default=Decimal("0.000"), max_digits=6),
                ),
                ("tax_identifier", models.CharField(blank=True, max_length=80)),
                ("is_active_tax", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="services.service",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "service_tax_configurations",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="service_cat_is_acti_fbdb6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(fields=["created_at"], name="service_cat_created_84c205_idx"),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(fields=["updated_at"], name="service_cat_updated_965294_idx"),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="service_cat_tenant__4ebf73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["tenant", "created_at"], name="service_cat_tenant__05d454_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicecategory",
            constraint=models.UniqueConstraint(
                fields=("tenant", "business", "slug"),
                name="uq_service_category_tenant_business_slug",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="services_is_acti_97b0e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["created_at"], name="services_created_22da02_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["updated_at"], name="services_updated_d331b2_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="services_tenant__bfa4dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["tenant", "created_at"], name="services_tenant__43974a_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["tenant", "business", "status"], name="services_tenant__04abae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["tenant", "business", "visibility"], name="services_tenant__7da5c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["tenant", "business", "service_code"], name="services_tenant__92c4bb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                fields=("tenant", "business", "service_code"),
                name="uq_service_tenant_business_code",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceimage",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="service_ima_is_acti_248101_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceimage",
            index=models.Index(fields=["created_at"], name="service_ima_created_5a76eb_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceimage",
            index=models.Index(fields=["updated_at"], name="service_ima_updated_40b409_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceimage",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="service_ima_tenant__da1aa8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceimage",
            index=models.Index(
                fields=["tenant", "created_at"], name="service_ima_tenant__b66f34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicetag",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="service_tag_is_acti_e4f941_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicetag",
            index=models.Index(fields=["created_at"], name="service_tag_created_785cd7_idx"),
        ),
        migrations.AddIndex(
            model_name="servicetag",
            index=models.Index(fields=["updated_at"], name="service_tag_updated_47e9cb_idx"),
        ),
        migrations.AddIndex(
            model_name="servicetag",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="service_tag_tenant__2d8eff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicetag",
            index=models.Index(
                fields=["tenant", "created_at"], name="service_tag_tenant__b32c83_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetag",
            constraint=models.UniqueConstraint(
                fields=("tenant", "business", "name"), name="uq_service_tag_tenant_business_name"
            ),
        ),
        migrations.AddIndex(
            model_name="servicevariant",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="service_var_is_acti_70d016_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicevariant",
            index=models.Index(fields=["created_at"], name="service_var_created_379658_idx"),
        ),
        migrations.AddIndex(
            model_name="servicevariant",
            index=models.Index(fields=["updated_at"], name="service_var_updated_5d0904_idx"),
        ),
        migrations.AddIndex(
            model_name="servicevariant",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="service_var_tenant__3107d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicevariant",
            index=models.Index(
                fields=["tenant", "created_at"], name="service_var_tenant__852eb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicepricing",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="service_pri_is_acti_886a1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicepricing",
            index=models.Index(fields=["created_at"], name="service_pri_created_6420fe_idx"),
        ),
        migrations.AddIndex(
            model_name="servicepricing",
            index=models.Index(fields=["updated_at"], name="service_pri_updated_c938ea_idx"),
        ),
        migrations.AddIndex(
            model_name="servicepricing",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="service_pri_tenant__0f0d46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicepricing",
            index=models.Index(
                fields=["tenant", "created_at"], name="service_pri_tenant__2fae1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceduration",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="service_dur_is_acti_ccf3e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceduration",
            index=models.Index(fields=["created_at"], name="service_dur_created_0f21e4_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceduration",
            index=models.Index(fields=["updated_at"], name="service_dur_updated_e2105b_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceduration",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="service_dur_tenant__6b6d71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceduration",
            index=models.Index(
                fields=["tenant", "created_at"], name="service_dur_tenant__d9263b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxconfiguration",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="service_tax_is_acti_25b01d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxconfiguration",
            index=models.Index(fields=["created_at"], name="service_tax_created_835b53_idx"),
        ),
        migrations.AddIndex(
            model_name="taxconfiguration",
            index=models.Index(fields=["updated_at"], name="service_tax_updated_3e071d_idx"),
        ),
        migrations.AddIndex(
            model_name="taxconfiguration",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="service_tax_tenant__444845_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxconfiguration",
            index=models.Index(
                fields=["tenant", "created_at"], name="service_tax_tenant__071d5c_idx"
            ),
        ),
    ]
