# Generated by Django 5.2.15 on 2026-07-04 18:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.db.uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tenant",
            old_name="name",
            new_name="display_name",
        ),
        migrations.RenameField(
            model_name="branding",
            old_name="logo_url",
            new_name="logo",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="default_timezone",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="default_currency",
        ),
        migrations.AddField(
            model_name="tenant",
            name="legal_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tenant",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_tenants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="timezone",
            field=models.CharField(default="UTC", max_length=64),
        ),
        migrations.AddField(
            model_name="tenant",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="tenant",
            name="language",
            field=models.CharField(default="en", max_length=16),
        ),
        migrations.AddField(
            model_name="tenant",
            name="country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="tenant",
            name="state",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="tenant",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="tenant",
            name="logo",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="favicon",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="primary_color",
            field=models.CharField(
                default="#0F6CBD",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color value.",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="secondary_color",
            field=models.CharField(
                default="#111827",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color value.",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="brand_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tenant",
            name="subscription_reference",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name="branding",
            name="dark_logo",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="branding",
            name="favicon",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="branding",
            name="theme_mode",
            field=models.CharField(
                choices=[("system", "System"), ("light", "Light"), ("dark", "Dark")],
                default="system",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="branding",
            name="typography_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="branding",
            name="brand_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="branding",
            name="white_label_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="branding",
            name="accent_color",
            field=models.CharField(
                blank=True,
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color value.",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="branding",
            name="primary_color",
            field=models.CharField(
                default="#0F6CBD",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color value.",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="branding",
            name="secondary_color",
            field=models.CharField(
                default="#111827",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color value.",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="branding",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenancy_branding_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="active",
                max_length=32,
            ),
        ),
        migrations.AlterModelOptions(
            name="tenant",
            options={"ordering": ["display_name"]},
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                ("business_category", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("alternate_phone", models.CharField(blank=True, max_length=32)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=32)),
                ("country", models.CharField(blank=True, max_length=120)),
                ("tax_identifier", models.CharField(blank=True, max_length=80)),
                ("tax_registration_type", models.CharField(blank=True, max_length=80)),
                ("website", models.URLField(blank=True)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenancy_organization_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={"db_table": "organizations", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("feature_flags", models.JSONField(blank=True, default=dict)),
                ("limits", models.JSONField(blank=True, default=dict)),
                ("is_public", models.BooleanField(default=True)),
            ],
            options={"db_table": "subscription_plans", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("suspended", "Suspended"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="trialing",
                        max_length=32,
                    ),
                ),
                ("trial_starts_at", models.DateTimeField(blank=True, null=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("current_period_starts_at", models.DateTimeField(blank=True, null=True)),
                ("current_period_ends_at", models.DateTimeField(blank=True, null=True)),
                ("renewal_date", models.DateField(blank=True, null=True)),
                ("feature_flags", models.JSONField(blank=True, default=dict)),
                ("limits", models.JSONField(blank=True, default=dict)),
                ("external_reference", models.CharField(blank=True, db_index=True, max_length=120)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="tenancy.subscriptionplan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenancy_subscription_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={"db_table": "subscriptions"},
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("business_hours", models.JSONField(blank=True, default=dict)),
                ("booking_preferences", models.JSONField(blank=True, default=dict)),
                ("localization", models.JSONField(blank=True, default=dict)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("language", models.CharField(default="en", max_length=16)),
                ("notification_defaults", models.JSONField(blank=True, default=dict)),
                ("security_preferences", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenancy_tenantsettings_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={"db_table": "tenant_settings"},
        ),
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("business_hours", models.JSONField(blank=True, default=dict)),
                ("booking_preferences", models.JSONField(blank=True, default=dict)),
                ("localization", models.JSONField(blank=True, default=dict)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("language", models.CharField(default="en", max_length=16)),
                ("notification_defaults", models.JSONField(blank=True, default=dict)),
                ("security_preferences", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenancy_organizationsettings_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={"db_table": "organization_settings"},
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["slug", "status"], name="tenants_slug_f70d36_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["owner", "status"], name="tenants_owner_i_bcb1f4_idx"),
        ),
        migrations.AddConstraint(
            model_name="branding",
            constraint=models.UniqueConstraint(fields=("tenant",), name="uq_branding_tenant"),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(fields=("tenant",), name="uq_organization_tenant"),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(fields=("tenant",), name="uq_subscription_tenant"),
        ),
        migrations.AddConstraint(
            model_name="tenantsettings",
            constraint=models.UniqueConstraint(
                fields=("tenant",),
                name="uq_tenant_settings_tenant",
            ),
        ),
    ]
