# Generated by Django 5.2.15 on 2026-07-04 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0002_m5_tenant_organization_platform"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tenant",
            new_name="tenants_slug_899f50_idx",
            old_name="tenants_slug_f70d36_idx",
        ),
        migrations.RenameIndex(
            model_name="tenant",
            new_name="tenants_owner_i_bcf8fd_idx",
            old_name="tenants_owner_i_bcb1f4_idx",
        ),
        migrations.AlterField(
            model_name="branding",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="branding",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="branding_is_acti_0c76eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branding",
            index=models.Index(fields=["created_at"], name="branding_created_380207_idx"),
        ),
        migrations.AddIndex(
            model_name="branding",
            index=models.Index(fields=["updated_at"], name="branding_updated_4123aa_idx"),
        ),
        migrations.AddIndex(
            model_name="branding",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="branding_tenant__e039ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branding",
            index=models.Index(fields=["tenant", "created_at"], name="branding_tenant__f7c318_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="organizatio_is_acti_23c1d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["created_at"], name="organizatio_created_8a4b5e_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["updated_at"], name="organizatio_updated_39d984_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="organizatio_tenant__9135ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["tenant", "created_at"], name="organizatio_tenant__9411e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationsettings",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="organizatio_is_acti_95859b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationsettings",
            index=models.Index(fields=["created_at"], name="organizatio_created_73a25e_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationsettings",
            index=models.Index(fields=["updated_at"], name="organizatio_updated_f51548_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationsettings",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="organizatio_tenant__5f0706_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationsettings",
            index=models.Index(
                fields=["tenant", "created_at"], name="organizatio_tenant__86e5cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="subscriptio_is_acti_388c24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["created_at"], name="subscriptio_created_ecfb9c_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["updated_at"], name="subscriptio_updated_92912e_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="subscriptio_tenant__ec6ae7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["tenant", "created_at"], name="subscriptio_tenant__a7e84f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="tenants_is_acti_5c9f82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["created_at"], name="tenants_created_fc84fe_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["updated_at"], name="tenants_updated_d341aa_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantsettings",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="tenant_sett_is_acti_c93711_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantsettings",
            index=models.Index(fields=["created_at"], name="tenant_sett_created_987b07_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantsettings",
            index=models.Index(fields=["updated_at"], name="tenant_sett_updated_edca62_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantsettings",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="tenant_sett_tenant__2e63e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantsettings",
            index=models.Index(
                fields=["tenant", "created_at"], name="tenant_sett_tenant__5adfaa_idx"
            ),
        ),
    ]
