# Generated by Django 5.2.16 on 2026-07-26 15:21

import apps.core.db.uuid
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0013_reward_points_loyalty"),
        ("customers", "0002_mobile_customer_features"),
        ("tenancy", "0004_expand_asset_url_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopOrder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_number", models.CharField(db_index=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("ready", "Ready"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "fulfillment_mode",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup"),
                            ("delivery", "Delivery"),
                            ("pos", "Point of Sale"),
                        ],
                        default="pickup",
                        max_length=32,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("delivery_address", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_orders",
                        to="businesses.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_orders",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_orders",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopInvoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(db_index=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("line_items", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_invoices",
                        to="businesses.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_invoices",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="shopie.shoporder",
                    ),
                ),
            ],
            options={
                "db_table": "shop_invoices",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopProduct",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sku", models.CharField(blank=True, db_index=True, max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("brand", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "stock_on_hand",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=12),
                ),
                (
                    "low_stock_threshold",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=12),
                ),
                ("pack_size", models.CharField(blank=True, max_length=80)),
                ("image_url", models.URLField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_products",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_products",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopOrderLine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("barcode_scanned", models.CharField(blank=True, max_length=128)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=Decimal("1"), max_digits=12),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                (
                    "line_subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "line_tax",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_order_lines",
                        to="businesses.business",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="shopie.shoporder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines",
                        to="shopie.shopproduct",
                    ),
                ),
            ],
            options={
                "db_table": "shop_order_lines",
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopProductBarcode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=128)),
                (
                    "barcode_type",
                    models.CharField(
                        choices=[
                            ("manufacturer", "Manufacturer"),
                            ("internal", "Internal"),
                            ("rfid_epc", "RFID EPC"),
                        ],
                        default="manufacturer",
                        max_length=32,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_product_barcodes",
                        to="businesses.business",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcodes",
                        to="shopie.shopproduct",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_product_barcodes",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopQuotation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quotation_number", models.CharField(db_index=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("converted", "Converted"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("line_items", models.JSONField(blank=True, default=list)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_quotations",
                        to="businesses.business",
                    ),
                ),
                (
                    "converted_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_quotations",
                        to="shopie.shoporder",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_quotations",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_quotations",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopStockMovement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("receive", "Receive"),
                            ("adjust", "Adjust"),
                            ("sale", "Sale"),
                            ("return", "Return"),
                            ("damage", "Damage"),
                        ],
                        max_length=32,
                    ),
                ),
                ("quantity_delta", models.DecimalField(decimal_places=3, max_digits=12)),
                ("quantity_after", models.DecimalField(decimal_places=3, max_digits=12)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_stock_movements",
                        to="businesses.business",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="shopie.shoporder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="shopie.shopproduct",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_stock_movements",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="shoporder",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_orders_is_acti_a7098c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoporder",
            index=models.Index(fields=["created_at"], name="shop_orders_created_2c07b9_idx"),
        ),
        migrations.AddIndex(
            model_name="shoporder",
            index=models.Index(fields=["updated_at"], name="shop_orders_updated_431c49_idx"),
        ),
        migrations.AddIndex(
            model_name="shoporder",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_orders_tenant__21d7b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoporder",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_orders_tenant__a6ee99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoporder",
            index=models.Index(
                fields=["tenant", "business", "status"], name="shop_orders_tenant__e0c754_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoporder",
            index=models.Index(
                fields=["tenant", "business", "order_number"], name="shop_orders_tenant__0da580_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopinvoice",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_invoic_is_acti_abe3c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopinvoice",
            index=models.Index(fields=["created_at"], name="shop_invoic_created_032890_idx"),
        ),
        migrations.AddIndex(
            model_name="shopinvoice",
            index=models.Index(fields=["updated_at"], name="shop_invoic_updated_22debc_idx"),
        ),
        migrations.AddIndex(
            model_name="shopinvoice",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_invoic_tenant__6f7ced_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopinvoice",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_invoic_tenant__234847_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopproduct",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_produc_is_acti_04cfce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopproduct",
            index=models.Index(fields=["created_at"], name="shop_produc_created_58a579_idx"),
        ),
        migrations.AddIndex(
            model_name="shopproduct",
            index=models.Index(fields=["updated_at"], name="shop_produc_updated_c31a58_idx"),
        ),
        migrations.AddIndex(
            model_name="shopproduct",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_produc_tenant__8dbb5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopproduct",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_produc_tenant__9e26b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopproduct",
            index=models.Index(
                fields=["tenant", "business", "status"], name="shop_produc_tenant__5d563d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopproduct",
            index=models.Index(
                fields=["tenant", "business", "name"], name="shop_produc_tenant__cd595f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoporderline",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_order__is_acti_e8260c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoporderline",
            index=models.Index(fields=["created_at"], name="shop_order__created_b0f91a_idx"),
        ),
        migrations.AddIndex(
            model_name="shoporderline",
            index=models.Index(fields=["updated_at"], name="shop_order__updated_2882a0_idx"),
        ),
        migrations.AddIndex(
            model_name="shoporderline",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_order__tenant__71c688_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoporderline",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_order__tenant__ca93f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopproductbarcode",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_produc_is_acti_b19fa8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopproductbarcode",
            index=models.Index(fields=["created_at"], name="shop_produc_created_b24787_idx"),
        ),
        migrations.AddIndex(
            model_name="shopproductbarcode",
            index=models.Index(fields=["updated_at"], name="shop_produc_updated_48fe7d_idx"),
        ),
        migrations.AddIndex(
            model_name="shopproductbarcode",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_produc_tenant__b1b911_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopproductbarcode",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_produc_tenant__2881b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopproductbarcode",
            index=models.Index(
                fields=["tenant", "business", "code"], name="shop_produc_tenant__413f24_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shopproductbarcode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("business", "code"),
                name="uq_shop_barcode_business_code_active",
            ),
        ),
        migrations.AddIndex(
            model_name="shopquotation",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_quotat_is_acti_9dd796_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopquotation",
            index=models.Index(fields=["created_at"], name="shop_quotat_created_c56e29_idx"),
        ),
        migrations.AddIndex(
            model_name="shopquotation",
            index=models.Index(fields=["updated_at"], name="shop_quotat_updated_c8ae16_idx"),
        ),
        migrations.AddIndex(
            model_name="shopquotation",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_quotat_tenant__b8c3a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopquotation",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_quotat_tenant__c30276_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopstockmovement",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_stock__is_acti_5be433_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopstockmovement",
            index=models.Index(fields=["created_at"], name="shop_stock__created_76fa48_idx"),
        ),
        migrations.AddIndex(
            model_name="shopstockmovement",
            index=models.Index(fields=["updated_at"], name="shop_stock__updated_493232_idx"),
        ),
        migrations.AddIndex(
            model_name="shopstockmovement",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_stock__tenant__12ae34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopstockmovement",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_stock__tenant__eaa213_idx"
            ),
        ),
    ]
