# Generated by Django 5.2.16 on 2026-07-26 15:30

import apps.core.db.uuid
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0013_reward_points_loyalty"),
        ("customers", "0002_mobile_customer_features"),
        ("shopie", "0001_initial_shopie"),
        ("tenancy", "0004_expand_asset_url_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("issued", "Issued"),
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Paid"),
                    ("credit", "Credit Note"),
                    ("void", "Void"),
                ],
                db_index=True,
                default="draft",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ShopBusinessSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled_packs", models.JSONField(blank=True, default=list)),
                (
                    "default_fulfillment_mode",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup"),
                            ("delivery", "Delivery"),
                            ("pos", "Point of Sale"),
                        ],
                        default="pickup",
                        max_length=32,
                    ),
                ),
                ("same_day_delivery_enabled", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_settings",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_business_settings",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="shop_busine_is_acti_f4efa0_idx"
                    ),
                    models.Index(fields=["created_at"], name="shop_busine_created_4ce6c7_idx"),
                    models.Index(fields=["updated_at"], name="shop_busine_updated_fea9d7_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="shop_busine_tenant__bea9f7_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="shop_busine_tenant__29f3b9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShopDeliveryZone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("enabled", models.BooleanField(default=True)),
                ("cities", models.JSONField(blank=True, default=list)),
                ("postal_prefixes", models.JSONField(blank=True, default=list)),
                ("same_day", models.BooleanField(default=True)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "min_order_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_delivery_zones",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_delivery_zones",
                "ordering": ["name"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="shop_delive_is_acti_98a1c9_idx"
                    ),
                    models.Index(fields=["created_at"], name="shop_delive_created_f63745_idx"),
                    models.Index(fields=["updated_at"], name="shop_delive_updated_594169_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="shop_delive_tenant__88996c_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="shop_delive_tenant__cb491b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShopPet",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("species", models.CharField(blank=True, max_length=80)),
                ("breed", models.CharField(blank=True, max_length=120)),
                ("sex", models.CharField(blank=True, max_length=32)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("medical_notes", models.TextField(blank=True)),
                ("medical_records", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_pets",
                        to="businesses.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_pets",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_pets",
                "ordering": ["name"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="shop_pets_is_acti_6e8738_idx"
                    ),
                    models.Index(fields=["created_at"], name="shop_pets_created_e6a6a0_idx"),
                    models.Index(fields=["updated_at"], name="shop_pets_updated_8e09a6_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="shop_pets_tenant__84da4b_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="shop_pets_tenant__dde6f7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShopReturn",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("return_number", models.CharField(db_index=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("restock", models.BooleanField(default=True)),
                (
                    "refund_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("line_items", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_returns",
                        to="businesses.business",
                    ),
                ),
                (
                    "credit_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_returns",
                        to="shopie.shopinvoice",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_returns",
                        to="customers.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="shopie.shoporder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_returns",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="shop_return_is_acti_f70ce7_idx"
                    ),
                    models.Index(fields=["created_at"], name="shop_return_created_bd9e02_idx"),
                    models.Index(fields=["updated_at"], name="shop_return_updated_55841d_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="shop_return_tenant__5df851_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="shop_return_tenant__c5ccb0_idx"
                    ),
                ],
            },
        ),
    ]
