# Generated by Django 5.2.17 on 2026-08-09 15:27

import apps.core.db.uuid
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0015_business_upi_payment_qr"),
        ("customers", "0003_customer_borrow_ledger"),
        ("shopie", "0007_shoppet_photo_url"),
        ("tenancy", "0004_expand_asset_url_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopBooksVoucher",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("purchase", "Purchase"),
                            ("payment_in", "Payment In"),
                            ("payment_out", "Payment Out"),
                            ("credit_note", "Credit Note"),
                            ("debit_note", "Debit Note"),
                            ("expense", "Expense"),
                            ("other_income", "Other Income"),
                            ("transfer", "Transfer"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("voucher_number", models.CharField(db_index=True, max_length=32)),
                ("voucher_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("confirmed", "Confirmed"), ("void", "Void")],
                        db_index=True,
                        default="confirmed",
                        max_length=16,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "cgst_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "sgst_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "igst_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                ("place_of_supply", models.CharField(blank=True, max_length=120)),
                ("is_interstate", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("line_items", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "shop_books_vouchers",
                "ordering": ["-voucher_date", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopCashAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("cash", "Cash"), ("bank", "Bank")], default="cash", max_length=16
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "shop_cash_accounts",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopPartyLedgerEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "party_kind",
                    models.CharField(
                        choices=[("customer", "Customer"), ("supplier", "Supplier")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("purchase", "Purchase"),
                            ("payment_in", "Payment In"),
                            ("payment_out", "Payment Out"),
                            ("credit", "Credit"),
                            ("debit", "Debit"),
                            ("adjustment", "Adjustment"),
                            ("opening", "Opening"),
                        ],
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "direction",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")], max_length=8
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "shop_party_ledger_entries",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopSupplier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=32)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("gstin", models.CharField(blank=True, db_index=True, max_length=20)),
                ("billing_state", models.CharField(blank=True, max_length=120)),
                ("billing_address", models.TextField(blank=True)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "shop_suppliers",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="batch_tracking_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="gst_rate",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="hsn_sac",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="shopbooksvoucher",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_books_vouchers",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="shopbooksvoucher",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_books_vouchers",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="shopbooksvoucher",
            name="linked_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books_vouchers",
                to="shopie.shopinvoice",
            ),
        ),
        migrations.AddField(
            model_name="shopbooksvoucher",
            name="linked_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books_vouchers",
                to="shopie.shoporder",
            ),
        ),
        migrations.AddField(
            model_name="shopbooksvoucher",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="shopcashaccount",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_cash_accounts",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="shopcashaccount",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="shopbooksvoucher",
            name="cash_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_books_vouchers",
                to="shopie.shopcashaccount",
            ),
        ),
        migrations.AddField(
            model_name="shopbooksvoucher",
            name="contra_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Destination account for transfer vouchers.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_books_vouchers_contra",
                to="shopie.shopcashaccount",
            ),
        ),
        migrations.AddField(
            model_name="shoppartyledgerentry",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_party_ledger_entries",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="shoppartyledgerentry",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_party_ledger_entries",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="shoppartyledgerentry",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="shoppartyledgerentry",
            name="voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="shopie.shopbooksvoucher",
            ),
        ),
        migrations.AddField(
            model_name="shopsupplier",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_suppliers",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="shopsupplier",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="shoppartyledgerentry",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_party_ledger_entries",
                to="shopie.shopsupplier",
            ),
        ),
        migrations.AddField(
            model_name="shopbooksvoucher",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_books_vouchers",
                to="shopie.shopsupplier",
            ),
        ),
        migrations.AddIndex(
            model_name="shopcashaccount",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_cash_a_is_acti_c6dd4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopcashaccount",
            index=models.Index(fields=["created_at"], name="shop_cash_a_created_569bd1_idx"),
        ),
        migrations.AddIndex(
            model_name="shopcashaccount",
            index=models.Index(fields=["updated_at"], name="shop_cash_a_updated_3d04b7_idx"),
        ),
        migrations.AddIndex(
            model_name="shopcashaccount",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_cash_a_tenant__2c7c56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopcashaccount",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_cash_a_tenant__4e6e24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopcashaccount",
            index=models.Index(
                fields=["tenant", "business", "account_type"], name="shop_cash_a_tenant__be1707_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopcashaccount",
            index=models.Index(
                fields=["tenant", "business", "is_active"], name="shop_cash_a_tenant__6c6cb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopsupplier",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_suppli_is_acti_331ff4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopsupplier",
            index=models.Index(fields=["created_at"], name="shop_suppli_created_197f41_idx"),
        ),
        migrations.AddIndex(
            model_name="shopsupplier",
            index=models.Index(fields=["updated_at"], name="shop_suppli_updated_626f8f_idx"),
        ),
        migrations.AddIndex(
            model_name="shopsupplier",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_suppli_tenant__9448c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopsupplier",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_suppli_tenant__8d9c8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopsupplier",
            index=models.Index(
                fields=["tenant", "business", "name"], name="shop_suppli_tenant__30140b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopsupplier",
            index=models.Index(
                fields=["tenant", "business", "phone"], name="shop_suppli_tenant__5c13a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopsupplier",
            index=models.Index(
                fields=["tenant", "business", "email"], name="shop_suppli_tenant__16f7a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopsupplier",
            index=models.Index(
                fields=["tenant", "business", "gstin"], name="shop_suppli_tenant__0d679e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoppartyledgerentry",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_party__is_acti_c25154_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoppartyledgerentry",
            index=models.Index(fields=["created_at"], name="shop_party__created_176163_idx"),
        ),
        migrations.AddIndex(
            model_name="shoppartyledgerentry",
            index=models.Index(fields=["updated_at"], name="shop_party__updated_797135_idx"),
        ),
        migrations.AddIndex(
            model_name="shoppartyledgerentry",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_party__tenant__4e071a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoppartyledgerentry",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_party__tenant__cc9930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoppartyledgerentry",
            index=models.Index(
                fields=["tenant", "business", "party_kind"], name="shop_party__tenant__68acb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoppartyledgerentry",
            index=models.Index(
                fields=["tenant", "business", "customer"], name="shop_party__tenant__713c9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoppartyledgerentry",
            index=models.Index(
                fields=["tenant", "business", "supplier"], name="shop_party__tenant__f36074_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopbooksvoucher",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_books__is_acti_aa8458_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopbooksvoucher",
            index=models.Index(fields=["created_at"], name="shop_books__created_e08697_idx"),
        ),
        migrations.AddIndex(
            model_name="shopbooksvoucher",
            index=models.Index(fields=["updated_at"], name="shop_books__updated_b11f32_idx"),
        ),
        migrations.AddIndex(
            model_name="shopbooksvoucher",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_books__tenant__fcee2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopbooksvoucher",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_books__tenant__04853d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopbooksvoucher",
            index=models.Index(
                fields=["tenant", "business", "voucher_type"], name="shop_books__tenant__afcfc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopbooksvoucher",
            index=models.Index(
                fields=["tenant", "business", "status"], name="shop_books__tenant__a965bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopbooksvoucher",
            index=models.Index(
                fields=["tenant", "business", "voucher_date"], name="shop_books__tenant__7fd0c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopbooksvoucher",
            index=models.Index(
                fields=["tenant", "business", "voucher_number"],
                name="shop_books__tenant__85ce00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shopbooksvoucher",
            index=models.Index(
                fields=["tenant", "business", "customer"], name="shop_books__tenant__d6166e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopbooksvoucher",
            index=models.Index(
                fields=["tenant", "business", "supplier"], name="shop_books__tenant__000ce3_idx"
            ),
        ),
    ]
