# Generated by Django 5.2.17 on 2026-08-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopie", "0008_gst_books"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="shopproduct",
            new_name="shop_produc_tenant__b4daf4_idx",
            old_name="shop_produc_tenant__catego_idx",
        ),
    ]
