# Generated by Django 5.2.17 on 2026-08-09 16:08

import apps.core.db.uuid
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0015_business_upi_payment_qr"),
        ("shopie", "0009_books_phase5_depth"),
        ("tenancy", "0004_expand_asset_url_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopProductBatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_number", models.CharField(db_index=True, max_length=64)),
                ("serial_number", models.CharField(blank=True, db_index=True, max_length=64)),
                ("manufactured_on", models.DateField(blank=True, null=True)),
                ("expires_on", models.DateField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=12),
                ),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "mrp",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_product_batches",
                        to="businesses.business",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="shopie.shopproduct",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_product_batches",
                "ordering": ["expires_on", "batch_number"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="shop_produc_is_acti_6e3d1f_idx"
                    ),
                    models.Index(fields=["created_at"], name="shop_produc_created_d216c1_idx"),
                    models.Index(fields=["updated_at"], name="shop_produc_updated_36925a_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="shop_produc_tenant__386bc5_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="shop_produc_tenant__8d4f82_idx"
                    ),
                    models.Index(
                        fields=["tenant", "business", "product"],
                        name="shop_produc_tenant__de563c_idx",
                    ),
                    models.Index(
                        fields=["tenant", "business", "batch_number"],
                        name="shop_produc_tenant__89c317_idx",
                    ),
                    models.Index(
                        fields=["tenant", "business", "expires_on"],
                        name="shop_produc_tenant__8a2ffb_idx",
                    ),
                ],
            },
        ),
    ]
