# Generated by Django 5.2.17 on 2026-08-09 16:25

import django.db.models.deletion
from django.db import migrations, models

import apps.core.db.uuid
import apps.shopie.models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0015_business_upi_payment_qr"),
        ("shopie", "0010_customer_gst_and_batches"),
        ("tenancy", "0004_expand_asset_url_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopbusinesssettings",
            name="einvoice_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shopbusinesssettings",
            name="eway_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shopbusinesssettings",
            name="gst_compliance",
            field=models.JSONField(blank=True, default=apps.shopie.models._default_gst_compliance),
        ),
        migrations.CreateModel(
            name="ShopEInvoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("generated", "Generated"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("INV", "Tax Invoice"),
                            ("CRN", "Credit Note"),
                            ("DBN", "Debit Note"),
                        ],
                        default="INV",
                        max_length=8,
                    ),
                ),
                ("irn", models.CharField(blank=True, db_index=True, max_length=128)),
                ("ack_no", models.CharField(blank=True, max_length=64)),
                ("ack_date", models.DateTimeField(blank=True, null=True)),
                ("signed_qr", models.TextField(blank=True)),
                ("signed_invoice", models.TextField(blank=True)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_einvoices",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "voucher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="einvoice",
                        to="shopie.shopbooksvoucher",
                    ),
                ),
            ],
            options={
                "db_table": "shop_einvoices",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopEWayBill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("ewb_no", models.CharField(blank=True, db_index=True, max_length=32)),
                ("ewb_date", models.DateTimeField(blank=True, null=True)),
                ("valid_upto", models.DateTimeField(blank=True, null=True)),
                (
                    "supply_type",
                    models.CharField(
                        choices=[("O", "Outward"), ("I", "Inward")], default="O", max_length=1
                    ),
                ),
                ("sub_supply_type", models.CharField(default="1", max_length=8)),
                ("doc_type", models.CharField(default="INV", max_length=8)),
                ("transporter_id", models.CharField(blank=True, max_length=20)),
                ("transporter_name", models.CharField(blank=True, max_length=200)),
                ("transport_mode", models.CharField(default="1", max_length=4)),
                ("vehicle_no", models.CharField(blank=True, max_length=20)),
                ("vehicle_type", models.CharField(blank=True, default="R", max_length=4)),
                ("distance_km", models.PositiveIntegerField(default=0)),
                ("from_place", models.CharField(blank=True, max_length=120)),
                ("from_state_code", models.CharField(blank=True, max_length=2)),
                ("to_place", models.CharField(blank=True, max_length=120)),
                ("to_state_code", models.CharField(blank=True, max_length=2)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_eway_bills",
                        to="businesses.business",
                    ),
                ),
                (
                    "einvoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eway_bills",
                        to="shopie.shopeinvoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eway_bills",
                        to="shopie.shopbooksvoucher",
                    ),
                ),
            ],
            options={
                "db_table": "shop_eway_bills",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="shopeinvoice",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_einvoi_is_acti_7c2b4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopeinvoice",
            index=models.Index(fields=["created_at"], name="shop_einvoi_created_13f061_idx"),
        ),
        migrations.AddIndex(
            model_name="shopeinvoice",
            index=models.Index(fields=["updated_at"], name="shop_einvoi_updated_b52221_idx"),
        ),
        migrations.AddIndex(
            model_name="shopeinvoice",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_einvoi_tenant__374a98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopeinvoice",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_einvoi_tenant__d3205e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopeinvoice",
            index=models.Index(
                fields=["tenant", "business", "status"], name="shop_einvoi_tenant__c42b34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopeinvoice",
            index=models.Index(
                fields=["tenant", "business", "irn"], name="shop_einvoi_tenant__edfdd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopewaybill",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_eway_b_is_acti_0c6e56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopewaybill",
            index=models.Index(fields=["created_at"], name="shop_eway_b_created_7e8452_idx"),
        ),
        migrations.AddIndex(
            model_name="shopewaybill",
            index=models.Index(fields=["updated_at"], name="shop_eway_b_updated_539245_idx"),
        ),
        migrations.AddIndex(
            model_name="shopewaybill",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_eway_b_tenant__4c15a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopewaybill",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_eway_b_tenant__4172d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopewaybill",
            index=models.Index(
                fields=["tenant", "business", "status"], name="shop_eway_b_tenant__4b4db4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopewaybill",
            index=models.Index(
                fields=["tenant", "business", "voucher"], name="shop_eway_b_tenant__cf6615_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopewaybill",
            index=models.Index(
                fields=["tenant", "business", "ewb_no"], name="shop_eway_b_tenant__da3e26_idx"
            ),
        ),
    ]
