# Generated by Django 5.2.17 on 2026-08-09 18:09

import apps.core.db.uuid
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0015_business_upi_payment_qr"),
        ("customers", "0005_customer_gst_and_batches"),
        ("shopie", "0011_einvoice_eway"),
        ("tenancy", "0004_expand_asset_url_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopGodown",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(blank=True, max_length=32)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_godowns",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_godowns",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopGodownStock",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=Decimal("0.000"), max_digits=14),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_godown_stocks",
                        to="businesses.business",
                    ),
                ),
                (
                    "godown",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="shopie.shopgodown",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="godown_stocks",
                        to="shopie.shopproduct",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_godown_stocks",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopLoan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "party_kind",
                    models.CharField(
                        choices=[("customer", "Customer"), ("supplier", "Supplier")],
                        default="customer",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("principal", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "interest_rate",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=7),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=14)),
                ("start_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("written_off", "Written off"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("repayments", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_loans",
                        to="businesses.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_loans",
                        to="customers.customer",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_loans",
                        to="shopie.shopsupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_loans",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopStockTransfer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transfer_number", models.CharField(db_index=True, max_length=32)),
                ("transfer_date", models.DateField()),
                ("status", models.CharField(default="completed", max_length=16)),
                ("notes", models.TextField(blank=True)),
                ("line_items", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_stock_transfers",
                        to="businesses.business",
                    ),
                ),
                (
                    "from_godown",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="shopie.shopgodown",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "to_godown",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="shopie.shopgodown",
                    ),
                ),
            ],
            options={
                "db_table": "shop_stock_transfers",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopBooksDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("sale_order", "Sale Order"),
                            ("purchase_order", "Purchase Order"),
                            ("delivery_challan", "Delivery Challan"),
                            ("job_work", "Job Work"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("document_number", models.CharField(db_index=True, max_length=32)),
                ("document_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("converted", "Converted"),
                            ("cancelled", "Cancelled"),
                            ("dispatched", "Dispatched"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                ("notes", models.TextField(blank=True)),
                ("line_items", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_books_documents",
                        to="businesses.business",
                    ),
                ),
                (
                    "converted_voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_documents",
                        to="shopie.shopbooksvoucher",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_books_documents",
                        to="customers.customer",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_books_documents",
                        to="shopie.shopsupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_books_documents",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="shop_books__is_acti_6929f6_idx"
                    ),
                    models.Index(fields=["created_at"], name="shop_books__created_bdd00e_idx"),
                    models.Index(fields=["updated_at"], name="shop_books__updated_028935_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="shop_books__tenant__53f11e_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="shop_books__tenant__66c7b3_idx"
                    ),
                    models.Index(
                        fields=["tenant", "business", "doc_type", "status"],
                        name="shop_books__tenant__935576_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShopCheque",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Cheque In"), ("out", "Cheque Out")],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("cleared", "Cleared"),
                            ("bounced", "Bounced"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("cheque_number", models.CharField(max_length=64)),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_cheques",
                        to="businesses.business",
                    ),
                ),
                (
                    "cash_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_cheques",
                        to="shopie.shopcashaccount",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_cheques",
                        to="customers.customer",
                    ),
                ),
                (
                    "linked_voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_cheques",
                        to="shopie.shopbooksvoucher",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_cheques",
                        to="shopie.shopsupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_cheques",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="shop_cheque_is_acti_36ae78_idx"
                    ),
                    models.Index(fields=["created_at"], name="shop_cheque_created_254981_idx"),
                    models.Index(fields=["updated_at"], name="shop_cheque_updated_acecdf_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="shop_cheque_tenant__7c59b6_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="shop_cheque_tenant__4e1741_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="shopgodown",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_godown_is_acti_fe4a26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopgodown",
            index=models.Index(fields=["created_at"], name="shop_godown_created_48411e_idx"),
        ),
        migrations.AddIndex(
            model_name="shopgodown",
            index=models.Index(fields=["updated_at"], name="shop_godown_updated_1844a1_idx"),
        ),
        migrations.AddIndex(
            model_name="shopgodown",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_godown_tenant__fafb0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopgodown",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_godown_tenant__844130_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopgodownstock",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_godown_is_acti_8bcd30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopgodownstock",
            index=models.Index(fields=["created_at"], name="shop_godown_created_b183aa_idx"),
        ),
        migrations.AddIndex(
            model_name="shopgodownstock",
            index=models.Index(fields=["updated_at"], name="shop_godown_updated_bc8685_idx"),
        ),
        migrations.AddIndex(
            model_name="shopgodownstock",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_godown_tenant__8ab16b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopgodownstock",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_godown_tenant__124cb3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shopgodownstock",
            constraint=models.UniqueConstraint(
                fields=("tenant", "business", "godown", "product"), name="uniq_shop_godown_stock"
            ),
        ),
        migrations.AddIndex(
            model_name="shoploan",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_loans_is_acti_2754da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoploan",
            index=models.Index(fields=["created_at"], name="shop_loans_created_7603bc_idx"),
        ),
        migrations.AddIndex(
            model_name="shoploan",
            index=models.Index(fields=["updated_at"], name="shop_loans_updated_772d1a_idx"),
        ),
        migrations.AddIndex(
            model_name="shoploan",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_loans_tenant__ed8080_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoploan",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_loans_tenant__74c7b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopstocktransfer",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_stock__is_acti_6242e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopstocktransfer",
            index=models.Index(fields=["created_at"], name="shop_stock__created_645c54_idx"),
        ),
        migrations.AddIndex(
            model_name="shopstocktransfer",
            index=models.Index(fields=["updated_at"], name="shop_stock__updated_df3e3b_idx"),
        ),
        migrations.AddIndex(
            model_name="shopstocktransfer",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_stock__tenant__d9ca8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopstocktransfer",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_stock__tenant__cb67e7_idx"
            ),
        ),
    ]
