# Generated by Django 5.2.17 on 2026-08-15 17:54

import apps.core.db.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0016_remove_crmie_invoiceie"),
        ("customers", "0005_customer_gst_and_batches"),
        ("platform_media", "0001_initial"),
        ("shopie", "0012_books_documents_godowns_cheques_loans"),
        ("tenancy", "0004_expand_asset_url_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerReferral",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("qualified", "Qualified"),
                            ("rewarded", "Rewarded"),
                            ("void", "Void"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("rewarded_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_referrals",
                        to="businesses.business",
                    ),
                ),
                (
                    "referred",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_received",
                        to="customers.customer",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_customer_referrals",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="shop_custom_is_acti_ba649a_idx"
                    ),
                    models.Index(fields=["created_at"], name="shop_custom_created_28587a_idx"),
                    models.Index(fields=["updated_at"], name="shop_custom_updated_c8c31c_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="shop_custom_tenant__153d68_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="shop_custom_tenant__0d9556_idx"
                    ),
                    models.Index(
                        fields=["tenant", "business", "status"],
                        name="shop_custom_tenant__07e20d_idx",
                    ),
                    models.Index(
                        fields=["tenant", "business", "referrer"],
                        name="shop_custom_tenant__92bf8f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "business", "referred"),
                        name="uq_shop_customer_referral_referred",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerReferralCode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=40)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_referral_codes",
                        to="businesses.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_codes",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_customer_referral_codes",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="shop_custom_is_acti_f5be78_idx"
                    ),
                    models.Index(fields=["created_at"], name="shop_custom_created_560952_idx"),
                    models.Index(fields=["updated_at"], name="shop_custom_updated_ae168c_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="shop_custom_tenant__94b8de_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="shop_custom_tenant__6d9f95_idx"
                    ),
                    models.Index(
                        fields=["tenant", "business", "code"], name="shop_custom_tenant__b72e01_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "business", "code"), name="uq_shop_customer_referral_code"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "business", "customer"),
                        name="uq_shop_customer_referral_code_customer",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShopDashboardAd",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("image_url", models.CharField(blank=True, max_length=1024)),
                ("link_url", models.CharField(blank=True, max_length=1024)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("starts_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_dashboard_ads",
                        to="businesses.business",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_dashboard_ads",
                        to="platform_media.media",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_dashboard_ads",
                "ordering": ["sort_order", "-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="shop_dashbo_is_acti_2a5ecf_idx"
                    ),
                    models.Index(fields=["created_at"], name="shop_dashbo_created_42c9aa_idx"),
                    models.Index(fields=["updated_at"], name="shop_dashbo_updated_ec4227_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="shop_dashbo_tenant__6a3249_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="shop_dashbo_tenant__7062d4_idx"
                    ),
                    models.Index(
                        fields=["tenant", "business", "is_active", "sort_order"],
                        name="shop_dashbo_tenant__246957_idx",
                    ),
                ],
            },
        ),
    ]
