# Generated by Django 5.2.17 on 2026-08-15 19:20

import apps.core.db.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0016_remove_crmie_invoiceie"),
        ("customers", "0005_customer_gst_and_batches"),
        ("shopie", "0013_grow_ads_referrals_slots_affiliates"),
        ("tenancy", "0004_expand_asset_url_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopProductReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_product_reviews",
                        to="businesses.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_product_reviews",
                        to="customers.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shopie.shopproduct",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_product_reviews",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="shopproductreview",
            constraint=models.CheckConstraint(
                check=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="ck_shop_product_review_rating_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="shopproductreview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant", "product", "customer"),
                name="uq_shop_product_review_customer_active",
            ),
        ),
        migrations.AddIndex(
            model_name="shopproductreview",
            index=models.Index(fields=["is_active", "deleted_at"], name="shop_produc_is_acti_rev1_idx"),
        ),
        migrations.AddIndex(
            model_name="shopproductreview",
            index=models.Index(fields=["created_at"], name="shop_produc_created_rev1_idx"),
        ),
        migrations.AddIndex(
            model_name="shopproductreview",
            index=models.Index(fields=["updated_at"], name="shop_produc_updated_rev1_idx"),
        ),
        migrations.AddIndex(
            model_name="shopproductreview",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"],
                name="shop_produc_tenant__rev1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shopproductreview",
            index=models.Index(fields=["tenant", "created_at"], name="shop_produc_tenant_c_rev1_idx"),
        ),
        migrations.AddIndex(
            model_name="shopproductreview",
            index=models.Index(fields=["tenant", "business", "product"], name="shop_produc_tenant_b_rev1_idx"),
        ),
    ]
