# Generated by Django 5.2.17 on 2026-08-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopie", "0014_shop_product_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopproduct",
            name="details_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="shopproductreview",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="shopproductreview",
            name="verified_purchase",
            field=models.BooleanField(default=False),
        ),
    ]
