# Generated by Django 5.2.17 on 2026-08-16 14:59

import apps.core.db.uuid
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0016_remove_crmie_invoiceie"),
        ("customers", "0005_customer_gst_and_batches"),
        ("shopie", "0015_product_details_html_review_title"),
        ("tenancy", "0004_expand_asset_url_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopCoupon",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("amount", "Fixed amount")],
                        default="percent",
                        max_length=16,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "min_order_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("starts_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("max_redemptions", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "max_redemptions_per_customer",
                    models.PositiveIntegerField(blank=True, default=1, null=True),
                ),
                ("first_order_only", models.BooleanField(default=False)),
                ("redemption_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "shop_coupons",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopCouponRedemption",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
            ],
            options={
                "db_table": "shop_coupon_redemptions",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="shopcoupon",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_coupons",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="shopcoupon",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="shopcouponredemption",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_coupon_redemptions",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="shopcouponredemption",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redemptions",
                to="shopie.shopcoupon",
            ),
        ),
        migrations.AddField(
            model_name="shopcouponredemption",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_coupon_redemptions",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="shopcouponredemption",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_redemption",
                to="shopie.shoporder",
            ),
        ),
        migrations.AddField(
            model_name="shopcouponredemption",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="shopcoupon",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_coupon_is_acti_899c4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopcoupon",
            index=models.Index(fields=["created_at"], name="shop_coupon_created_d4e306_idx"),
        ),
        migrations.AddIndex(
            model_name="shopcoupon",
            index=models.Index(fields=["updated_at"], name="shop_coupon_updated_739196_idx"),
        ),
        migrations.AddIndex(
            model_name="shopcoupon",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_coupon_tenant__093c8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopcoupon",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_coupon_tenant__1715d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopcoupon",
            index=models.Index(
                fields=["tenant", "business", "code"], name="shop_coupon_tenant__4085a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopcoupon",
            index=models.Index(
                fields=["tenant", "business", "is_active"], name="shop_coupon_tenant__21b8f5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shopcoupon",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant", "business", "code"),
                name="uq_shop_coupon_code_active",
            ),
        ),
        migrations.AddIndex(
            model_name="shopcouponredemption",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_coupon_is_acti_c9dc6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopcouponredemption",
            index=models.Index(fields=["created_at"], name="shop_coupon_created_6582bb_idx"),
        ),
        migrations.AddIndex(
            model_name="shopcouponredemption",
            index=models.Index(fields=["updated_at"], name="shop_coupon_updated_8ddca0_idx"),
        ),
        migrations.AddIndex(
            model_name="shopcouponredemption",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_coupon_tenant__7e4210_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopcouponredemption",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_coupon_tenant__3facb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopcouponredemption",
            index=models.Index(
                fields=["tenant", "business", "coupon"], name="shop_coupon_tenant__67511b_idx"
            ),
        ),
    ]
