# Generated by Django 5.2.17 on 2026-08-21 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0016_remove_crmie_invoiceie"),
        ("shopie", "0019_delivery_webhook_retries"),
        ("tenancy", "0004_expand_asset_url_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopgodown",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_godowns",
                to="businesses.branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="shopgodown",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch__isnull", False)),
                fields=("tenant", "business", "branch"),
                name="uniq_shop_godown_per_branch",
            ),
        ),
    ]
