# Generated by Django 5.2.17 on 2026-08-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopie', '0023_order_delivery_address_door_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ready', 'Ready'), ('out_for_delivery', 'Out for Delivery'), ('delivery_failed', 'Delivery Failed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32),
        ),
    ]
