# Generated by Django 5.2.17 on 2026-08-23 18:43

import django.db.models.deletion
from django.db import migrations, models
from django.utils.dateparse import parse_datetime

import apps.core.db.uuid


def _as_datetime(value, fallback):
    parsed = parse_datetime(str(value or ""))
    return parsed or fallback


def backfill_tracking_history(apps, schema_editor):
    ShopOrder = apps.get_model("shopie", "ShopOrder")
    ShopDeliveryAttempt = apps.get_model("shopie", "ShopDeliveryAttempt")
    ShopOrderTrackingEvent = apps.get_model("shopie", "ShopOrderTrackingEvent")

    orders = ShopOrder.objects.filter(fulfillment_mode="delivery").iterator(chunk_size=200)
    for order in orders:
        metadata = order.metadata if isinstance(order.metadata, dict) else {}
        delivery = metadata.get("delivery") if isinstance(metadata.get("delivery"), dict) else {}
        attempts = []
        previous_end = order.created_at
        for number, snapshot in enumerate(delivery.get("attempts") or [], start=1):
            if not isinstance(snapshot, dict):
                continue
            ended_at = _as_datetime(snapshot.get("ended_at"), order.updated_at)
            attempt = ShopDeliveryAttempt.objects.create(
                tenant_id=order.tenant_id,
                business_id=order.business_id,
                order_id=order.id,
                attempt_number=number,
                provider=str(delivery.get("provider") or ""),
                booking_id=str(snapshot.get("booking_id") or ""),
                status=str(snapshot.get("partner_status") or "failed"),
                rider=snapshot.get("rider") if isinstance(snapshot.get("rider"), dict) else {},
                reason=str(snapshot.get("reason") or ""),
                started_at=previous_end,
                ended_at=ended_at,
            )
            attempts.append(attempt)
            previous_end = ended_at

        if delivery.get("booking_id"):
            attempt = ShopDeliveryAttempt.objects.create(
                tenant_id=order.tenant_id,
                business_id=order.business_id,
                order_id=order.id,
                attempt_number=len(attempts) + 1,
                provider=str(delivery.get("provider") or ""),
                booking_id=str(delivery.get("booking_id") or ""),
                status=("delivered" if delivery.get("partner_status") == "delivered" else "active"),
                tracking_url=str(delivery.get("tracking_url") or ""),
                rider=delivery.get("rider") if isinstance(delivery.get("rider"), dict) else {},
                reason=str(delivery.get("reason") or ""),
                started_at=previous_end,
                ended_at=(
                    order.updated_at if delivery.get("partner_status") == "delivered" else None
                ),
            )
            attempts.append(attempt)

        raw_events = delivery.get("events") if isinstance(delivery.get("events"), list) else []
        if not raw_events:
            raw_events = [
                {
                    "status": "order_placed",
                    "label": "Order placed",
                    "occurred_at": order.created_at.isoformat(),
                }
            ]
        for index, raw in enumerate(raw_events):
            if not isinstance(raw, dict):
                continue
            occurred_at = _as_datetime(raw.get("occurred_at"), order.created_at)
            attempt = None
            for candidate in attempts:
                if candidate.ended_at and occurred_at <= candidate.ended_at:
                    attempt = candidate
                    break
            if attempt is None and attempts:
                attempt = attempts[-1]
            label = str(raw.get("label") or "")
            status = str(raw.get("status") or "")
            if label.lower() == "order placed":
                status = "order_placed"
            ShopOrderTrackingEvent.objects.create(
                tenant_id=order.tenant_id,
                business_id=order.business_id,
                order_id=order.id,
                attempt_id=attempt.id if attempt else None,
                kind="status",
                status=status,
                label=label or status.replace("_", " ").title(),
                source="migration",
                source_key=f"legacy:{index}:{occurred_at.isoformat()}",
                occurred_at=occurred_at,
                reason=str(raw.get("reason") or ""),
            )


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0016_remove_crmie_invoiceie"),
        ("shopie", "0024_order_delivery_failed_status"),
        ("tenancy", "0004_expand_asset_url_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopDeliveryAttempt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("provider", models.CharField(blank=True, db_index=True, max_length=32)),
                ("booking_id", models.CharField(blank=True, db_index=True, max_length=180)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
                ("tracking_url", models.URLField(blank=True, max_length=1000)),
                ("rider", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_delivery_attempts",
                        to="businesses.business",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="shopie.shoporder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "shop_delivery_attempts",
                "ordering": ["attempt_number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopOrderTrackingEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("status", "Status"), ("location", "Location")],
                        db_index=True,
                        default="status",
                        max_length=16,
                    ),
                ),
                ("status", models.CharField(blank=True, db_index=True, max_length=40)),
                ("label", models.CharField(blank=True, max_length=160)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("order", "Order"),
                            ("dispatch", "Dispatch"),
                            ("webhook", "Webhook"),
                            ("poll", "Poll"),
                            ("simulation", "Simulation"),
                            ("migration", "Migration"),
                        ],
                        db_index=True,
                        default="order",
                        max_length=20,
                    ),
                ),
                ("source_key", models.CharField(blank=True, max_length=220)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                ("eta_minutes", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="shopie.shopdeliveryattempt",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_order_tracking_events",
                        to="businesses.business",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="shopie.shoporder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "webhook_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_events",
                        to="shopie.shopdeliverywebhookevent",
                    ),
                ),
            ],
            options={
                "db_table": "shop_order_tracking_events",
                "ordering": ["occurred_at", "created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="shopdeliveryattempt",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_delive_is_acti_a2777b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopdeliveryattempt",
            index=models.Index(fields=["created_at"], name="shop_delive_created_3a0fd1_idx"),
        ),
        migrations.AddIndex(
            model_name="shopdeliveryattempt",
            index=models.Index(fields=["updated_at"], name="shop_delive_updated_3f111d_idx"),
        ),
        migrations.AddIndex(
            model_name="shopdeliveryattempt",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_delive_tenant__e4274f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopdeliveryattempt",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_delive_tenant__b09efc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopdeliveryattempt",
            index=models.Index(
                fields=["business", "status", "started_at"], name="shop_delive_busines_28fd91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopdeliveryattempt",
            index=models.Index(
                fields=["provider", "booking_id"], name="shop_delive_provide_c9d3da_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shopdeliveryattempt",
            constraint=models.UniqueConstraint(
                fields=("order", "attempt_number"), name="uq_shop_delivery_attempt_order_number"
            ),
        ),
        migrations.AddIndex(
            model_name="shopordertrackingevent",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="shop_order__is_acti_66040a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopordertrackingevent",
            index=models.Index(fields=["created_at"], name="shop_order__created_0d9e54_idx"),
        ),
        migrations.AddIndex(
            model_name="shopordertrackingevent",
            index=models.Index(fields=["updated_at"], name="shop_order__updated_94b5ec_idx"),
        ),
        migrations.AddIndex(
            model_name="shopordertrackingevent",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="shop_order__tenant__e32dae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopordertrackingevent",
            index=models.Index(
                fields=["tenant", "created_at"], name="shop_order__tenant__804edd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopordertrackingevent",
            index=models.Index(
                fields=["order", "kind", "occurred_at"], name="shop_order__order_i_ce7ae9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopordertrackingevent",
            index=models.Index(
                fields=["attempt", "kind", "occurred_at"], name="shop_order__attempt_01be45_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shopordertrackingevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_key", ""), _negated=True),
                fields=("order", "source_key"),
                name="uq_shop_tracking_order_source_key",
            ),
        ),
        migrations.RunPython(backfill_tracking_history, migrations.RunPython.noop),
    ]
