# Generated by Django 5.2.17 on 2026-09-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopie', '0027_shop_business_settings_cod_enabled'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shoporder',
            new_name='shop_orders_tenant__5c42eb_idx',
            old_name='shop_orders_tenant_business_created_idx',
        ),
    ]
