# Generated by Django 5.2.17 on 2026-09-17 15:20

import apps.core.db.uuid
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0017_businesssettings_whatsapp_integration'),
        ('shopie', '0030_shop_shipment_audit_fields'),
        ('tenancy', '0004_expand_asset_url_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformGtinCatalog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('pack_size', models.CharField(blank=True, max_length=80)),
                ('serving_size', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('details_html', models.TextField(blank=True)),
                ('categories', models.CharField(blank=True, help_text='Raw catalog category string', max_length=500)),
                ('category', models.CharField(blank=True, help_text='Resolved ShopProductCategory slug', max_length=64)),
                ('category_label', models.CharField(blank=True, max_length=120)),
                ('hsn_sac', models.CharField(blank=True, max_length=16)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('mrp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('image_url', models.CharField(blank=True, max_length=1024)),
                ('images', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('confidence', models.CharField(blank=True, default='none', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'platform_gtin_catalog',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ShopProductCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('is_builtin', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'db_table': 'shop_product_categories',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SmartLookupUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('found', models.BooleanField(default=False)),
                ('charged_paise', models.IntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('usd_micros', models.PositiveIntegerField(default=0, help_text='USD cost × 1_000_000')),
                ('model', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'smart_lookup_usage',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmartLookupWallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('balance_paise', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'smart_lookup_wallets',
                'abstract': False,
            },
        ),
        migrations.RenameIndex(
            model_name='shopshipment',
            new_name='shop_shipme_is_acti_68fc98_idx',
            old_name='shop_shipments_active_del_idx',
        ),
        migrations.RenameIndex(
            model_name='shopshipment',
            new_name='shop_shipme_tenant__0b395e_idx',
            old_name='shop_shipments_tenant_active_idx',
        ),
        migrations.RenameIndex(
            model_name='shopshipment',
            new_name='shop_shipme_tenant__be676e_idx',
            old_name='shop_shipments_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='shopshipment',
            new_name='shop_shipme_busines_a4bbf0_idx',
            old_name='shop_shipments_biz_status_idx',
        ),
        migrations.RenameIndex(
            model_name='shopshipment',
            new_name='shop_shipme_carrier_b648e9_idx',
            old_name='shop_shipments_carrier_awb_idx',
        ),
        migrations.AddField(
            model_name='shopbusinesssettings',
            name='smart_lookup_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='shopshipment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='shopshipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='shopshipment',
            index=models.Index(fields=['created_at'], name='shop_shipme_created_bc968f_idx'),
        ),
        migrations.AddIndex(
            model_name='shopshipment',
            index=models.Index(fields=['updated_at'], name='shop_shipme_updated_55bd1b_idx'),
        ),
        migrations.AddField(
            model_name='smartlookupusage',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_lookup_usages', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='smartlookupusage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='smartlookupwallet',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smart_lookup_wallet', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='smartlookupwallet',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='smartlookupusage',
            index=models.Index(fields=['is_active', 'deleted_at'], name='smart_looku_is_acti_f6976d_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlookupusage',
            index=models.Index(fields=['created_at'], name='smart_looku_created_25b2c8_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlookupusage',
            index=models.Index(fields=['updated_at'], name='smart_looku_updated_02f49a_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlookupusage',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='smart_looku_tenant__483d07_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlookupusage',
            index=models.Index(fields=['tenant', 'created_at'], name='smart_looku_tenant__608a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlookupusage',
            index=models.Index(fields=['tenant', 'business', 'created_at'], name='smart_looku_tenant__ff80b9_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlookupwallet',
            index=models.Index(fields=['is_active', 'deleted_at'], name='smart_looku_is_acti_f21a57_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlookupwallet',
            index=models.Index(fields=['created_at'], name='smart_looku_created_4724fb_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlookupwallet',
            index=models.Index(fields=['updated_at'], name='smart_looku_updated_fb540d_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlookupwallet',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='smart_looku_tenant__6507cb_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlookupwallet',
            index=models.Index(fields=['tenant', 'created_at'], name='smart_looku_tenant__575cca_idx'),
        ),
    ]
