# Generated by Django 5.2.17 on 2026-09-25 07:05

import apps.core.db.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0018_business_billing_gst_fields'),
        ('shopie', '0032_smart_lookup_balance_after'),
        ('tenancy', '0004_expand_asset_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='unit',
            field=models.CharField(blank=True, help_text='Shop master unit slug or label (pcs, kg, …)', max_length=32),
        ),
        migrations.CreateModel(
            name='ShopMasterRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('category', 'Product category'), ('brand', 'Brand'), ('unit', 'Unit'), ('expense_category', 'Expense category'), ('income_category', 'Income category'), ('tax_rate', 'Tax rate')], db_index=True, max_length=32)),
                ('slug', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(blank=True, help_text='Optional typed value (e.g. tax rate percent as string).', max_length=64)),
                ('is_builtin', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_master_records', to='businesses.business')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'shop_master_records',
                'ordering': ['kind', 'sort_order', 'label'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'deleted_at'], name='shop_master_is_acti_1d0059_idx'), models.Index(fields=['created_at'], name='shop_master_created_086b77_idx'), models.Index(fields=['updated_at'], name='shop_master_updated_6ac6da_idx'), models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='shop_master_tenant__0a8f0f_idx'), models.Index(fields=['tenant', 'created_at'], name='shop_master_tenant__e1ce43_idx'), models.Index(fields=['tenant', 'business', 'kind', 'is_active'], name='shop_master_tenant__d5a59f_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'business', 'kind', 'slug'), name='uniq_shop_master_kind_slug')],
            },
        ),
    ]
