# Generated by Django 5.2.17 on 2026-09-25 12:42

import apps.core.db.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0018_business_billing_gst_fields'),
        ('shopie', '0033_shop_master_records_and_product_unit'),
        ('tenancy', '0004_expand_asset_url_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDocumentShareLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('sale', 'Sale invoice'), ('quotation', 'Quotation'), ('delivery_challan', 'Delivery challan')], db_index=True, max_length=32)),
                ('document_id', models.UUIDField(db_index=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_views', models.PositiveIntegerField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_document_share_links', to='businesses.business')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'shop_document_share_links',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'deleted_at'], name='shop_docume_is_acti_01d1c9_idx'), models.Index(fields=['created_at'], name='shop_docume_created_eeecfb_idx'), models.Index(fields=['updated_at'], name='shop_docume_updated_9f4d83_idx'), models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='shop_docume_tenant__2a24d8_idx'), models.Index(fields=['tenant', 'created_at'], name='shop_docume_tenant__c35eb5_idx'), models.Index(fields=['tenant', 'business', 'kind', 'document_id'], name='shop_docume_tenant__d84a81_idx')],
            },
        ),
    ]
