# Generated by Django 5.2.17 on 2026-09-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopie', '0034_shop_document_share_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcoupon',
            name='applies_to_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopcoupon',
            name='applies_to_pos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopcoupon',
            name='eligibility',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
