# Generated by Django 5.2.17 on 2026-10-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopie", "0037_platform_gtin_catalog_currency_import_runs"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="platformgtinimportrun",
            name="platform_gt_is_acti_imp1_idx",
        ),
        migrations.RemoveIndex(
            model_name="platformgtinimportrun",
            name="platform_gt_created_imp1_idx",
        ),
        migrations.RemoveIndex(
            model_name="platformgtinimportrun",
            name="platform_gt_updated_imp1_idx",
        ),
        migrations.RenameIndex(
            model_name="platformgtincatalog",
            new_name="platform_gt_name_8b69c9_idx",
            old_name="platform_gt_name_8f0a1c_idx",
        ),
        migrations.RenameIndex(
            model_name="platformgtincatalog",
            new_name="platform_gt_brand_9c2ec3_idx",
            old_name="platform_gt_brand_1c9e2d_idx",
        ),
        migrations.RenameIndex(
            model_name="platformgtincatalog",
            new_name="platform_gt_categor_61edfc_idx",
            old_name="platform_gt_categor_4a7b3e_idx",
        ),
        migrations.RenameIndex(
            model_name="platformgtincatalog",
            new_name="platform_gt_source_cda7ff_idx",
            old_name="platform_gt_source_6d2f5a_idx",
        ),
        migrations.AlterField(
            model_name="shopmasterrecord",
            name="kind",
            field=models.CharField(
                choices=[
                    ("category", "Product category"),
                    ("brand", "Brand"),
                    ("unit", "Unit"),
                    ("expense_category", "Expense category"),
                    ("income_category", "Income category"),
                    ("tax_rate", "Tax rate"),
                    ("pet_species", "Pet species"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
