# Generated by Django 5.2.15 on 2026-07-05 05:39

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.db.uuid
import apps.staff.validators.staff


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("platform_media", "0001_initial"),
        ("services", "0001_initial"),
        ("tenancy", "0003_rename_tenants_slug_f70d36_idx_tenants_slug_899f50_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessRole",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("receptionist", "Receptionist"),
                            ("stylist", "Stylist"),
                            ("therapist", "Therapist"),
                            ("technician", "Technician"),
                            ("consultant", "Consultant"),
                            ("assistant", "Assistant"),
                            ("read_only", "Read Only"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("is_system", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "business_roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("staff_code", models.SlugField(max_length=80)),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("display_name", models.CharField(max_length=160)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, db_index=True, max_length=32)),
                ("designation", models.CharField(blank=True, max_length=120)),
                ("department", models.CharField(blank=True, db_index=True, max_length=120)),
                ("working_location", models.CharField(blank=True, max_length=160)),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_leave", "On Leave"),
                            ("terminated", "Terminated"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
                ("emergency_contact", models.JSONField(blank=True, default=dict)),
                ("preferences", models.JSONField(blank=True, default=dict)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.staff.validators.staff.validate_tags],
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="businesses.business",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_photos",
                        to="platform_media.media",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "staff",
                "ordering": ["display_name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmploymentDetails",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("intern", "Intern"),
                            ("consultant", "Consultant"),
                        ],
                        default="full_time",
                        max_length=32,
                    ),
                ),
                ("contract_start", models.DateField(blank=True, null=True)),
                ("contract_end", models.DateField(blank=True, null=True)),
                ("salary_metadata", models.JSONField(blank=True, default=dict)),
                ("payroll_reference", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment",
                        to="staff.staff",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "db_table": "staff_employment_details",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StaffCertification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("issuing_authority", models.CharField(blank=True, max_length=160)),
                ("issued_at", models.DateField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_certificates",
                        to="platform_media.media",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="staff.staff",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "staff_certifications",
                "ordering": ["-issued_at", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StaffDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_type", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=160)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_documents",
                        to="platform_media.media",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="staff.staff",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "staff_documents",
                "ordering": ["title"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StaffNote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField()),
                ("is_internal", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="staff.staff",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "staff_notes",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=32)),
                ("address", models.JSONField(blank=True, default=dict)),
                ("skills_summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="staff.staff",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "staff_profiles",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StaffRoleAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="staff.businessrole",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="staff.staff",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "staff_role_assignments",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StaffServiceAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("default_duration_override", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "default_price_override",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("priority", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active_assignment", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_assignments",
                        to="services.service",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_assignments",
                        to="staff.staff",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "staff_service_assignments",
                "ordering": ["priority", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StaffSkill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=32,
                    ),
                ),
                (
                    "years_experience",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                ("certification_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_skills",
                        to="services.service",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="staff.staff",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "staff_skills",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(fields=["is_active", "deleted_at"], name="staff_is_acti_ec430d_idx"),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(fields=["created_at"], name="staff_created_bceb2b_idx"),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(fields=["updated_at"], name="staff_updated_b3e682_idx"),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="staff_tenant__7a95d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(fields=["tenant", "created_at"], name="staff_tenant__049ef2_idx"),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["tenant", "business", "employment_status"], name="staff_tenant__504026_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["tenant", "business", "staff_code"], name="staff_tenant__92be95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["tenant", "business", "email"], name="staff_tenant__226e95_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.UniqueConstraint(
                fields=("tenant", "business", "staff_code"), name="uq_staff_tenant_business_code"
            ),
        ),
        migrations.AddIndex(
            model_name="employmentdetails",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="staff_emplo_is_acti_cc7db3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employmentdetails",
            index=models.Index(fields=["created_at"], name="staff_emplo_created_f0dcd6_idx"),
        ),
        migrations.AddIndex(
            model_name="employmentdetails",
            index=models.Index(fields=["updated_at"], name="staff_emplo_updated_a4d061_idx"),
        ),
        migrations.AddIndex(
            model_name="employmentdetails",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="staff_emplo_tenant__6fc8c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employmentdetails",
            index=models.Index(
                fields=["tenant", "created_at"], name="staff_emplo_tenant__263212_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffcertification",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="staff_certi_is_acti_7df809_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffcertification",
            index=models.Index(fields=["created_at"], name="staff_certi_created_da337b_idx"),
        ),
        migrations.AddIndex(
            model_name="staffcertification",
            index=models.Index(fields=["updated_at"], name="staff_certi_updated_5c8dc9_idx"),
        ),
        migrations.AddIndex(
            model_name="staffcertification",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="staff_certi_tenant__dc5367_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffcertification",
            index=models.Index(
                fields=["tenant", "created_at"], name="staff_certi_tenant__1d1b48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffdocument",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="staff_docum_is_acti_1a46ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffdocument",
            index=models.Index(fields=["created_at"], name="staff_docum_created_78ef65_idx"),
        ),
        migrations.AddIndex(
            model_name="staffdocument",
            index=models.Index(fields=["updated_at"], name="staff_docum_updated_730f2e_idx"),
        ),
        migrations.AddIndex(
            model_name="staffdocument",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="staff_docum_tenant__d533af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffdocument",
            index=models.Index(
                fields=["tenant", "created_at"], name="staff_docum_tenant__2ca272_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffnote",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="staff_notes_is_acti_5d271e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffnote",
            index=models.Index(fields=["created_at"], name="staff_notes_created_5446ac_idx"),
        ),
        migrations.AddIndex(
            model_name="staffnote",
            index=models.Index(fields=["updated_at"], name="staff_notes_updated_717cdb_idx"),
        ),
        migrations.AddIndex(
            model_name="staffnote",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="staff_notes_tenant__119c56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffnote",
            index=models.Index(
                fields=["tenant", "created_at"], name="staff_notes_tenant__cecb5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="staff_profi_is_acti_20bf1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(fields=["created_at"], name="staff_profi_created_20e736_idx"),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(fields=["updated_at"], name="staff_profi_updated_9f7225_idx"),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="staff_profi_tenant__b80555_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(
                fields=["tenant", "created_at"], name="staff_profi_tenant__c0f43e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffroleassignment",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="staff_role__is_acti_35c094_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffroleassignment",
            index=models.Index(fields=["created_at"], name="staff_role__created_26bfba_idx"),
        ),
        migrations.AddIndex(
            model_name="staffroleassignment",
            index=models.Index(fields=["updated_at"], name="staff_role__updated_412aa4_idx"),
        ),
        migrations.AddIndex(
            model_name="staffroleassignment",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="staff_role__tenant__efc6b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffroleassignment",
            index=models.Index(
                fields=["tenant", "created_at"], name="staff_role__tenant__849475_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffroleassignment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "staff", "role"), name="uq_staff_role_assignment"
            ),
        ),
        migrations.AddIndex(
            model_name="staffserviceassignment",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="staff_servi_is_acti_fa5aa3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffserviceassignment",
            index=models.Index(fields=["created_at"], name="staff_servi_created_05ca28_idx"),
        ),
        migrations.AddIndex(
            model_name="staffserviceassignment",
            index=models.Index(fields=["updated_at"], name="staff_servi_updated_3439fe_idx"),
        ),
        migrations.AddIndex(
            model_name="staffserviceassignment",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="staff_servi_tenant__cf2363_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffserviceassignment",
            index=models.Index(
                fields=["tenant", "created_at"], name="staff_servi_tenant__927b30_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffserviceassignment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "staff", "service"), name="uq_staff_service_assignment"
            ),
        ),
        migrations.AddIndex(
            model_name="staffskill",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="staff_skill_is_acti_427472_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffskill",
            index=models.Index(fields=["created_at"], name="staff_skill_created_5be78f_idx"),
        ),
        migrations.AddIndex(
            model_name="staffskill",
            index=models.Index(fields=["updated_at"], name="staff_skill_updated_252929_idx"),
        ),
        migrations.AddIndex(
            model_name="staffskill",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="staff_skill_tenant__7463e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffskill",
            index=models.Index(
                fields=["tenant", "created_at"], name="staff_skill_tenant__bc12b4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffskill",
            constraint=models.UniqueConstraint(
                fields=("tenant", "staff", "service"), name="uq_staff_skill_staff_service"
            ),
        ),
    ]
