# Generated by Django 5.2.15 on 2026-07-07 07:11

import apps.core.db.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "businesses",
            "0006_remove_businessproductsubscription_business_pr_tenant__8f0f0a_idx_and_more",
        ),
        ("staff", "0002_seed_business_roles"),
        ("tenancy", "0003_rename_tenants_slug_f70d36_idx_tenants_slug_899f50_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffInvitation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("platform_role_code", models.SlugField(max_length=80)),
                ("token", models.UUIDField(db_index=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_invitations",
                        to="businesses.business",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_staff_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations",
                        to="staff.staff",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "staff_invitations",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="staff_invit_is_acti_d9b752_idx"
                    ),
                    models.Index(fields=["created_at"], name="staff_invit_created_c7994d_idx"),
                    models.Index(fields=["updated_at"], name="staff_invit_updated_908858_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="staff_invit_tenant__12680c_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="staff_invit_tenant__29f3e7_idx"
                    ),
                    models.Index(
                        fields=["tenant", "business", "status"],
                        name="staff_invit_tenant__96b12a_idx",
                    ),
                    models.Index(
                        fields=["tenant", "email", "status"], name="staff_invit_tenant__a40df6_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("tenant", "business", "email"),
                        name="uq_staff_invitation_pending_email",
                    )
                ],
            },
        ),
    ]
