# Generated by Django 5.2.16 on 2026-07-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_staffinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="is_bookable",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="When false, this person does not consume a staff seat and cannot be assigned to bookings.",
            ),
        ),
    ]
