# Generated by Django 5.2.15 on 2026-07-07 07:11

import apps.core.db.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0003_rename_tenants_slug_f70d36_idx_tenants_slug_899f50_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("action", models.CharField(db_index=True, max_length=120)),
                ("resource_type", models.CharField(db_index=True, max_length=120)),
                ("resource_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "audit_log_entries",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="audit_log_e_is_acti_c574bb_idx"
                    ),
                    models.Index(fields=["created_at"], name="audit_log_e_created_8db7a2_idx"),
                    models.Index(fields=["updated_at"], name="audit_log_e_updated_cfc04c_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="audit_log_e_tenant__279cbf_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="audit_log_e_tenant__a3521a_idx"
                    ),
                    models.Index(
                        fields=["tenant", "action", "created_at"],
                        name="audit_log_e_tenant__c38c7f_idx",
                    ),
                    models.Index(
                        fields=["tenant", "resource_type", "resource_id"],
                        name="audit_log_e_tenant__a54559_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DomainEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=160)),
                ("aggregate_type", models.CharField(db_index=True, max_length=120)),
                ("aggregate_id", models.CharField(db_index=True, max_length=120)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "domain_events",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="domain_even_is_acti_5242fe_idx"
                    ),
                    models.Index(fields=["created_at"], name="domain_even_created_406dbf_idx"),
                    models.Index(fields=["updated_at"], name="domain_even_updated_03b976_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="domain_even_tenant__beef44_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="domain_even_tenant__7f8e9d_idx"
                    ),
                    models.Index(
                        fields=["tenant", "event_type", "status"],
                        name="domain_even_tenant__64375a_idx",
                    ),
                    models.Index(
                        fields=["tenant", "aggregate_type", "aggregate_id"],
                        name="domain_even_tenant__3cdfe9_idx",
                    ),
                ],
            },
        ),
    ]
