# Generated by Django 5.2.17 on 2026-09-01 19:43

import apps.core.db.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0016_remove_crmie_invoiceie'),
        ('calendar', '0001_initial'),
        ('tenancy', '0004_expand_asset_url_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarconnection',
            name='id',
            field=models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calendarconnection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='calendarselection',
            name='id',
            field=models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calendarselection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='calendarconnection',
            index=models.Index(fields=['is_active', 'deleted_at'], name='calendar_co_is_acti_9f61b5_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarconnection',
            index=models.Index(fields=['created_at'], name='calendar_co_created_fd548f_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarconnection',
            index=models.Index(fields=['updated_at'], name='calendar_co_updated_5ca533_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarconnection',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='calendar_co_tenant__675e55_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarconnection',
            index=models.Index(fields=['tenant', 'created_at'], name='calendar_co_tenant__422033_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarselection',
            index=models.Index(fields=['is_active', 'deleted_at'], name='calendar_se_is_acti_0f4132_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarselection',
            index=models.Index(fields=['created_at'], name='calendar_se_created_7e00b8_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarselection',
            index=models.Index(fields=['updated_at'], name='calendar_se_updated_991e54_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarselection',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='calendar_se_tenant__95c592_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarselection',
            index=models.Index(fields=['tenant', 'created_at'], name='calendar_se_tenant__2b8fcf_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarconnection',
            constraint=models.UniqueConstraint(fields=('tenant', 'business', 'provider'), name='uq_calendar_connection_tenant_business_provider'),
        ),
        migrations.AddConstraint(
            model_name='calendarselection',
            constraint=models.UniqueConstraint(fields=('tenant', 'business', 'calendar_id'), name='uq_calendar_selection_tenant_business_calendar'),
        ),
    ]
