# Generated by Django 5.2.15 on 2026-07-07 07:11

import apps.core.db.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0005_branch_and_dashboard_preferences"),
        ("tenancy", "0003_rename_tenants_slug_f70d36_idx_tenants_slug_899f50_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingCheckoutSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_code", models.SlugField(max_length=80)),
                ("plan_code", models.SlugField(max_length=80)),
                ("razorpay_order_id", models.CharField(max_length=120, unique=True)),
                ("amount_paise", models.PositiveIntegerField()),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=32,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_checkout_sessions",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "billing_checkout_sessions",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_active", "deleted_at"], name="billing_che_is_acti_fb8bfd_idx"
                    ),
                    models.Index(fields=["created_at"], name="billing_che_created_5da5b8_idx"),
                    models.Index(fields=["updated_at"], name="billing_che_updated_62ff07_idx"),
                    models.Index(
                        fields=["tenant", "is_active", "deleted_at"],
                        name="billing_che_tenant__231b65_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="billing_che_tenant__00e399_idx"
                    ),
                    models.Index(
                        fields=["tenant", "business", "status"],
                        name="billing_che_tenant__4b6096_idx",
                    ),
                    models.Index(
                        fields=["razorpay_order_id"], name="billing_che_razorpa_1e982f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BillingWebhookEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(default="razorpay", max_length=32)),
                ("external_event_id", models.CharField(max_length=120, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=120)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=32,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_webhook_events",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "billing_webhook_events",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["provider", "event_type", "status"],
                        name="billing_web_provide_5d7b43_idx",
                    )
                ],
            },
        ),
    ]
