# Generated by Django 5.2.17 on 2026-09-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billingcheckoutsession_cashfree_order_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billingcheckoutsession',
            new_name='billing_che_cashfre_9b7e98_idx',
            old_name='billing_che_cashfre_idx',
        ),
    ]
