# Generated by Django 5.2.17 on 2026-09-25 12:58

import apps.core.db.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0018_business_billing_gst_fields'),
        ('tenancy', '0004_expand_asset_url_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('product_code', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused')], db_index=True, default='draft', max_length=16)),
                ('trigger', models.JSONField(blank=True, default=dict)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('created_via', models.CharField(choices=[('manual', 'Manual'), ('gemini', 'Gemini'), ('template', 'Template')], default='manual', max_length=16)),
                ('source_prompt', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_definitions', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_definitions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'workflow_definitions',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('trigger_key', models.CharField(db_index=True, max_length=80)),
                ('subject_type', models.CharField(blank=True, max_length=40)),
                ('subject_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='succeeded', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=191)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='businesses.business')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workflow.workflowdefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'workflow_runs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=apps.core.db.uuid.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('source_prompt', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_usages', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_usages', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'workflow_usages',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['is_active', 'deleted_at'], name='workflow_de_is_acti_e98b67_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['created_at'], name='workflow_de_created_d16658_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['updated_at'], name='workflow_de_updated_b95fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='workflow_de_tenant__1ce194_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['tenant', 'created_at'], name='workflow_de_tenant__ec678d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['tenant', 'business', 'status'], name='workflow_de_tenant__0f8993_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['tenant', 'business', 'product_code'], name='workflow_de_tenant__f6bb49_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['is_active', 'deleted_at'], name='workflow_ru_is_acti_8947ab_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['created_at'], name='workflow_ru_created_27295f_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['updated_at'], name='workflow_ru_updated_fe517e_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='workflow_ru_tenant__85547a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['tenant', 'created_at'], name='workflow_ru_tenant__a4645a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['tenant', 'business', 'created_at'], name='workflow_ru_tenant__f237e0_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['tenant', 'definition', 'created_at'], name='workflow_ru_tenant__259706_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowrun',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('idempotency_key', ''), _negated=True)), fields=('tenant', 'business', 'idempotency_key'), name='uq_workflow_run_idempotency'),
        ),
        migrations.AddIndex(
            model_name='workflowusage',
            index=models.Index(fields=['is_active', 'deleted_at'], name='workflow_us_is_acti_cfd20b_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowusage',
            index=models.Index(fields=['created_at'], name='workflow_us_created_92a86b_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowusage',
            index=models.Index(fields=['updated_at'], name='workflow_us_updated_4ad0f7_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowusage',
            index=models.Index(fields=['tenant', 'is_active', 'deleted_at'], name='workflow_us_tenant__949a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowusage',
            index=models.Index(fields=['tenant', 'created_at'], name='workflow_us_tenant__c76a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowusage',
            index=models.Index(fields=['tenant', 'business', 'created_at'], name='workflow_us_tenant__0228ad_idx'),
        ),
    ]
