# Generated by Django 5.2.15 on 2026-07-05 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.db.uuid
import apps.customers.validators.customers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("platform_media", "0001_initial"),
        ("tenancy", "0003_rename_tenants_slug_f70d36_idx_tenants_slug_899f50_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_code", models.SlugField(max_length=80)),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("display_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, db_index=True, max_length=32)),
                ("alternate_phone", models.CharField(blank=True, max_length=32)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("not_specified", "Not Specified"),
                            ("female", "Female"),
                            ("male", "Male"),
                            ("non_binary", "Non-binary"),
                            ("other", "Other"),
                        ],
                        default="not_specified",
                        max_length=32,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("blocked", "Blocked"),
                            ("archived", "Archived"),
                            ("merged", "Merged"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.customers.validators.customers.validate_tags],
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers",
                        to="businesses.business",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merged_customers",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "customers",
                "ordering": ["display_name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("billing", "Billing"),
                            ("other", "Other"),
                        ],
                        default="home",
                        max_length=32,
                    ),
                ),
                ("line1", models.CharField(max_length=255)),
                ("line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, db_index=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(blank=True, db_index=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=32)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "customer_addresses",
                "ordering": ["-is_default", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerCommunicationPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("phone", "Phone"),
                            ("push", "Push"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("opt_in_at", models.DateTimeField(blank=True, null=True)),
                ("opt_out_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_channels",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "customer_communication_preferences",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerExportJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_export_jobs",
                        to="businesses.business",
                    ),
                ),
                (
                    "result_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_export_jobs",
                        to="platform_media.media",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "customer_export_jobs",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerImportJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("processed_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                ("mapping", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_import_jobs",
                        to="businesses.business",
                    ),
                ),
                (
                    "source_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_import_jobs",
                        to="platform_media.media",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "customer_import_jobs",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerMergeRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_merge_records",
                        to="businesses.business",
                    ),
                ),
                (
                    "merged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_merges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merge_records_as_source",
                        to="customers.customer",
                    ),
                ),
                (
                    "target_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merge_records_as_target",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "customer_merge_records",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField()),
                ("is_internal", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "customer_notes",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerPreferences",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("language", models.CharField(default="en", max_length=16)),
                ("booking_preferences", models.JSONField(blank=True, default=dict)),
                ("communication_preferences", models.JSONField(blank=True, default=dict)),
                ("marketing_opt_in", models.BooleanField(default=False)),
                ("accessibility_preferences", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "customer_preferences",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=120)),
                ("company", models.CharField(blank=True, max_length=160)),
                ("about", models.TextField(blank=True)),
                ("preferences_summary", models.TextField(blank=True)),
                ("internal_reference", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="customers.customer",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_profiles",
                        to="platform_media.media",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "customer_profiles",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("color", models.CharField(blank=True, max_length=16)),
                ("description", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_tags",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "customer_tags",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="customers_is_acti_e8a15c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["created_at"], name="customers_created_c63477_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["updated_at"], name="customers_updated_a69b42_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="customers_tenant__6f45a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "created_at"], name="customers_tenant__bac0f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "business", "status"], name="customers_tenant__fc291d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "business", "email"], name="customers_tenant__d12da3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "business", "phone_number"], name="customers_tenant__b6e07d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "business", "customer_code"], name="customers_tenant__b3c298_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("tenant", "business", "customer_code"),
                name="uq_customer_tenant_business_code",
            ),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="customer_ad_is_acti_a620d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(fields=["created_at"], name="customer_ad_created_91e1e8_idx"),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(fields=["updated_at"], name="customer_ad_updated_4e04ca_idx"),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="customer_ad_tenant__bfa673_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["tenant", "created_at"], name="customer_ad_tenant__4e8c47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customercommunicationpreference",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="customer_co_is_acti_3dfe9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customercommunicationpreference",
            index=models.Index(fields=["created_at"], name="customer_co_created_3e8de8_idx"),
        ),
        migrations.AddIndex(
            model_name="customercommunicationpreference",
            index=models.Index(fields=["updated_at"], name="customer_co_updated_e1f2f1_idx"),
        ),
        migrations.AddIndex(
            model_name="customercommunicationpreference",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="customer_co_tenant__26892e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customercommunicationpreference",
            index=models.Index(
                fields=["tenant", "created_at"], name="customer_co_tenant__6ebe9f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customercommunicationpreference",
            constraint=models.UniqueConstraint(
                fields=("tenant", "customer", "channel"), name="uq_customer_communication_channel"
            ),
        ),
        migrations.AddIndex(
            model_name="customerexportjob",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="customer_ex_is_acti_b9272b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerexportjob",
            index=models.Index(fields=["created_at"], name="customer_ex_created_9affb1_idx"),
        ),
        migrations.AddIndex(
            model_name="customerexportjob",
            index=models.Index(fields=["updated_at"], name="customer_ex_updated_32a4ee_idx"),
        ),
        migrations.AddIndex(
            model_name="customerexportjob",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="customer_ex_tenant__7536c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerexportjob",
            index=models.Index(
                fields=["tenant", "created_at"], name="customer_ex_tenant__4b98cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerimportjob",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="customer_im_is_acti_0584bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerimportjob",
            index=models.Index(fields=["created_at"], name="customer_im_created_749ee8_idx"),
        ),
        migrations.AddIndex(
            model_name="customerimportjob",
            index=models.Index(fields=["updated_at"], name="customer_im_updated_801a53_idx"),
        ),
        migrations.AddIndex(
            model_name="customerimportjob",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="customer_im_tenant__5bfafb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerimportjob",
            index=models.Index(
                fields=["tenant", "created_at"], name="customer_im_tenant__9245d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customermergerecord",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="customer_me_is_acti_bf0c0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customermergerecord",
            index=models.Index(fields=["created_at"], name="customer_me_created_d9f335_idx"),
        ),
        migrations.AddIndex(
            model_name="customermergerecord",
            index=models.Index(fields=["updated_at"], name="customer_me_updated_8ab108_idx"),
        ),
        migrations.AddIndex(
            model_name="customermergerecord",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="customer_me_tenant__b50cdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customermergerecord",
            index=models.Index(
                fields=["tenant", "created_at"], name="customer_me_tenant__b53282_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customernote",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="customer_no_is_acti_48af72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customernote",
            index=models.Index(fields=["created_at"], name="customer_no_created_9353bf_idx"),
        ),
        migrations.AddIndex(
            model_name="customernote",
            index=models.Index(fields=["updated_at"], name="customer_no_updated_1b5f84_idx"),
        ),
        migrations.AddIndex(
            model_name="customernote",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="customer_no_tenant__837cab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customernote",
            index=models.Index(
                fields=["tenant", "created_at"], name="customer_no_tenant__922a4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerpreferences",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="customer_pr_is_acti_d07b67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerpreferences",
            index=models.Index(fields=["created_at"], name="customer_pr_created_aa7305_idx"),
        ),
        migrations.AddIndex(
            model_name="customerpreferences",
            index=models.Index(fields=["updated_at"], name="customer_pr_updated_5155ee_idx"),
        ),
        migrations.AddIndex(
            model_name="customerpreferences",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="customer_pr_tenant__f13324_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerpreferences",
            index=models.Index(
                fields=["tenant", "created_at"], name="customer_pr_tenant__10a3db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="customer_pr_is_acti_ae651d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(fields=["created_at"], name="customer_pr_created_9d0a1e_idx"),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(fields=["updated_at"], name="customer_pr_updated_9ea9b0_idx"),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="customer_pr_tenant__b355e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["tenant", "created_at"], name="customer_pr_tenant__0f615e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customertag",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="customer_ta_is_acti_a5ab81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customertag",
            index=models.Index(fields=["created_at"], name="customer_ta_created_42f8b4_idx"),
        ),
        migrations.AddIndex(
            model_name="customertag",
            index=models.Index(fields=["updated_at"], name="customer_ta_updated_159372_idx"),
        ),
        migrations.AddIndex(
            model_name="customertag",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="customer_ta_tenant__db91e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customertag",
            index=models.Index(
                fields=["tenant", "created_at"], name="customer_ta_tenant__7ea27a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customertag",
            constraint=models.UniqueConstraint(
                fields=("tenant", "business", "name"), name="uq_customer_tag_tenant_business_name"
            ),
        ),
    ]
