# Generated by Django 5.2.16 on 2026-07-25 09:10

import apps.core.db.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0009_expand_asset_url_fields"),
        ("customers", "0001_initial"),
        ("tenancy", "0004_expand_asset_url_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerLoyaltyAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("points_balance", models.PositiveIntegerField(default=0)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_accounts",
                        to="businesses.business",
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_account",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "customer_loyalty_accounts",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerLoyaltyLedger",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("points_delta", models.IntegerField()),
                ("reason", models.CharField(max_length=160)),
                ("booking_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="customers.customerloyaltyaccount",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_ledger_entries",
                        to="businesses.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_ledger_entries",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "customer_loyalty_ledger",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="customerloyaltyaccount",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="customer_lo_is_acti_48bfce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerloyaltyaccount",
            index=models.Index(fields=["created_at"], name="customer_lo_created_441ed5_idx"),
        ),
        migrations.AddIndex(
            model_name="customerloyaltyaccount",
            index=models.Index(fields=["updated_at"], name="customer_lo_updated_a5be52_idx"),
        ),
        migrations.AddIndex(
            model_name="customerloyaltyaccount",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="customer_lo_tenant__67c087_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerloyaltyaccount",
            index=models.Index(
                fields=["tenant", "created_at"], name="customer_lo_tenant__7a0070_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customerloyaltyaccount",
            constraint=models.UniqueConstraint(
                fields=("tenant", "business", "customer"),
                name="uq_loyalty_account_tenant_business_customer",
            ),
        ),
        migrations.AddIndex(
            model_name="customerloyaltyledger",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="customer_lo_is_acti_2c59c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerloyaltyledger",
            index=models.Index(fields=["created_at"], name="customer_lo_created_45a1f8_idx"),
        ),
        migrations.AddIndex(
            model_name="customerloyaltyledger",
            index=models.Index(fields=["updated_at"], name="customer_lo_updated_19896d_idx"),
        ),
        migrations.AddIndex(
            model_name="customerloyaltyledger",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="customer_lo_tenant__76fce1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerloyaltyledger",
            index=models.Index(
                fields=["tenant", "created_at"], name="customer_lo_tenant__f7e098_idx"
            ),
        ),
    ]
