# Generated by Django 5.2.17 on 2026-08-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0015_business_upi_payment_qr"),
        ("customers", "0003_customer_borrow_ledger"),
        ("tenancy", "0004_expand_asset_url_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerborrowaccount",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="customerborrowledger",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="customerborrowaccount",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="customer_bo_is_acti_1a43ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerborrowaccount",
            index=models.Index(fields=["created_at"], name="customer_bo_created_270b38_idx"),
        ),
        migrations.AddIndex(
            model_name="customerborrowaccount",
            index=models.Index(fields=["updated_at"], name="customer_bo_updated_ca19fe_idx"),
        ),
        migrations.AddIndex(
            model_name="customerborrowaccount",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="customer_bo_tenant__faa426_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerborrowaccount",
            index=models.Index(
                fields=["tenant", "created_at"], name="customer_bo_tenant__37d7e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerborrowledger",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="customer_bo_is_acti_023017_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerborrowledger",
            index=models.Index(fields=["created_at"], name="customer_bo_created_80b4c2_idx"),
        ),
        migrations.AddIndex(
            model_name="customerborrowledger",
            index=models.Index(fields=["updated_at"], name="customer_bo_updated_a34b3f_idx"),
        ),
        migrations.AddIndex(
            model_name="customerborrowledger",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="customer_bo_tenant__b803d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerborrowledger",
            index=models.Index(
                fields=["tenant", "created_at"], name="customer_bo_tenant__23d7df_idx"
            ),
        ),
    ]
