# Generated by Django 5.2.17 on 2026-08-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_books_phase5_depth"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="billing_state",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="customer",
            name="gstin",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
