from django.urls import path

from apps.api.mobile_views import (
    MobileAvailabilityView,
    MobileBookingCancelView,
    MobileBookingDetailView,
    MobileBookingListView,
    MobileBookingRequestView,
    MobileBookingRescheduleView,
    MobileBookingReviewCreateView,
    MobileBootstrapView,
    MobileBranchesListView,
    MobileCustomerAddressDetailView,
    MobileCustomerAddressListCreateView,
    MobileCustomerProfilePhotoView,
    MobileCustomerProfileView,
    MobileCustomerRegisterView,
    MobileDeviceRegisterView,
    MobileDeviceUnregisterView,
    MobileDiscoverServiceDetailView,
    MobileDiscoverServicesView,
    MobileLoyaltyQuoteView,
    MobileLoyaltyView,
    MobileMyReviewsView,
    MobileNotificationListView,
    MobileNotificationMarkReadView,
    MobileNotificationReadAllView,
    MobileStaffListView,
)
from apps.notifications.api.stream_views import MobileNotificationStreamView
from apps.shopie.api.delivery_views import (
    MobileShopDeliveryQuoteView,
    MobileShopOrderDeliveryLiveView,
)
from apps.shopie.api.mobile_views import (
    MobileShopAdListView,
    MobileShopCouponAvailableView,
    MobileShopCouponValidateView,
    MobileShopDeliveryZoneMatchView,
    MobileShopDeliveryHintView,
    MobileShopOrderCancelView,
    MobileShopOrderClaimPaymentView,
    MobileShopOrderDetailView,
    MobileShopOrderListCreateView,
    MobileShopOrderPaymentProofView,
    MobileShopPetDetailView,
    MobileShopPetListView,
    MobileShopPetPhotoView,
    MobileShopProductDetailView,
    MobileShopProductListView,
    MobileShopProductReviewListCreateView,
    MobileShopReferralApplyView,
    MobileShopReferralView,
    MobileShopReturnDetailView,
    MobileShopReturnListView,
    MobileUpiPreviewView,
)

urlpatterns = [
    path("mobile/bootstrap", MobileBootstrapView.as_view(), name="mobile-bootstrap"),
    path("mobile/auth/register", MobileCustomerRegisterView.as_view(), name="mobile-customer-register"),
    path("mobile/customer/profile", MobileCustomerProfileView.as_view(), name="mobile-customer-profile"),
    path(
        "mobile/customer/profile/photo",
        MobileCustomerProfilePhotoView.as_view(),
        name="mobile-customer-profile-photo",
    ),
    path(
        "mobile/customer/addresses",
        MobileCustomerAddressListCreateView.as_view(),
        name="mobile-customer-addresses",
    ),
    path(
        "mobile/customer/addresses/<uuid:address_id>",
        MobileCustomerAddressDetailView.as_view(),
        name="mobile-customer-address-detail",
    ),
    path("mobile/loyalty", MobileLoyaltyView.as_view(), name="mobile-loyalty"),
    path("mobile/loyalty/quote", MobileLoyaltyQuoteView.as_view(), name="mobile-loyalty-quote"),
    path("mobile/reviews/mine", MobileMyReviewsView.as_view(), name="mobile-reviews-mine"),
    path("mobile/devices/register", MobileDeviceRegisterView.as_view(), name="mobile-devices-register"),
    path("mobile/devices/unregister", MobileDeviceUnregisterView.as_view(), name="mobile-devices-unregister"),
    path("mobile/discover/services", MobileDiscoverServicesView.as_view(), name="mobile-discover-services"),
    path(
        "mobile/discover/services/<uuid:service_id>",
        MobileDiscoverServiceDetailView.as_view(),
        name="mobile-discover-service-detail",
    ),
    path("mobile/staff", MobileStaffListView.as_view(), name="mobile-staff-list"),
    path("mobile/branches", MobileBranchesListView.as_view(), name="mobile-branches-list"),
    path("mobile/availability", MobileAvailabilityView.as_view(), name="mobile-availability"),
    path("mobile/bookings", MobileBookingListView.as_view(), name="mobile-booking-list"),
    path("mobile/bookings/<uuid:booking_id>", MobileBookingDetailView.as_view(), name="mobile-booking-detail"),
    path("mobile/bookings/<uuid:booking_id>/cancel", MobileBookingCancelView.as_view(), name="mobile-booking-cancel"),
    path(
        "mobile/bookings/<uuid:booking_id>/reschedule",
        MobileBookingRescheduleView.as_view(),
        name="mobile-booking-reschedule",
    ),
    path(
        "mobile/bookings/<uuid:booking_id>/reviews",
        MobileBookingReviewCreateView.as_view(),
        name="mobile-booking-review-create",
    ),
    path("mobile/bookings/request", MobileBookingRequestView.as_view(), name="mobile-booking-request"),
    path("mobile/notifications/stream", MobileNotificationStreamView.as_view(), name="mobile-notification-stream"),
    path("mobile/notifications", MobileNotificationListView.as_view(), name="mobile-notification-list"),
    path("mobile/notifications/read-all", MobileNotificationReadAllView.as_view(), name="mobile-notification-read-all"),
    path(
        "mobile/notifications/<uuid:notification_id>/read",
        MobileNotificationMarkReadView.as_view(),
        name="mobile-notification-mark-read",
    ),
    path("mobile/shop/ads", MobileShopAdListView.as_view(), name="mobile-shop-ads"),
    path("mobile/shop/referral", MobileShopReferralView.as_view(), name="mobile-shop-referral"),
    path(
        "mobile/shop/referral/apply",
        MobileShopReferralApplyView.as_view(),
        name="mobile-shop-referral-apply",
    ),
    path("mobile/shop/products", MobileShopProductListView.as_view(), name="mobile-shop-products"),
    path(
        "mobile/shop/products/<uuid:product_id>",
        MobileShopProductDetailView.as_view(),
        name="mobile-shop-product-detail",
    ),
    path(
        "mobile/shop/products/<uuid:product_id>/reviews",
        MobileShopProductReviewListCreateView.as_view(),
        name="mobile-shop-product-reviews",
    ),
    path("mobile/shop/orders", MobileShopOrderListCreateView.as_view(), name="mobile-shop-orders"),
    path(
        "mobile/shop/coupons/validate",
        MobileShopCouponValidateView.as_view(),
        name="mobile-shop-coupon-validate",
    ),
    path(
        "mobile/shop/coupons/available",
        MobileShopCouponAvailableView.as_view(),
        name="mobile-shop-coupon-available",
    ),
    path(
        "mobile/shop/orders/<uuid:order_id>",
        MobileShopOrderDetailView.as_view(),
        name="mobile-shop-order-detail",
    ),
    path(
        "mobile/shop/orders/<uuid:order_id>/delivery-live",
        MobileShopOrderDeliveryLiveView.as_view(),
        name="mobile-shop-order-delivery-live",
    ),
    path(
        "mobile/shop/orders/<uuid:order_id>/cancel",
        MobileShopOrderCancelView.as_view(),
        name="mobile-shop-order-cancel",
    ),
    path(
        "mobile/shop/orders/<uuid:order_id>/claim-payment",
        MobileShopOrderClaimPaymentView.as_view(),
        name="mobile-shop-order-claim-payment",
    ),
    path(
        "mobile/shop/orders/<uuid:order_id>/payment-proof",
        MobileShopOrderPaymentProofView.as_view(),
        name="mobile-shop-order-payment-proof",
    ),
    path(
        "mobile/shop/delivery-hint",
        MobileShopDeliveryHintView.as_view(),
        name="mobile-shop-delivery-hint",
    ),
    path(
        "mobile/shop/delivery-zones/match",
        MobileShopDeliveryZoneMatchView.as_view(),
        name="mobile-shop-delivery-zone-match",
    ),
    path(
        "mobile/shop/delivery/quote",
        MobileShopDeliveryQuoteView.as_view(),
        name="mobile-shop-delivery-quote",
    ),
    path("mobile/shop/pets", MobileShopPetListView.as_view(), name="mobile-shop-pets"),
    path("mobile/shop/pets/photo", MobileShopPetPhotoView.as_view(), name="mobile-shop-pet-photo"),
    path(
        "mobile/shop/pets/<uuid:pet_id>",
        MobileShopPetDetailView.as_view(),
        name="mobile-shop-pet-detail",
    ),
    path("mobile/shop/returns", MobileShopReturnListView.as_view(), name="mobile-shop-returns"),
    path(
        "mobile/shop/returns/<uuid:return_id>",
        MobileShopReturnDetailView.as_view(),
        name="mobile-shop-return-detail",
    ),
    path("mobile/shop/upi-preview", MobileUpiPreviewView.as_view(), name="mobile-shop-upi-preview"),
]
