from django.urls import path

from apps.billing.api.views import (
    BillingCheckoutView,
    BillingGoLiveCheckView,
    BillingObservabilityView,
    BillingOpsDigestView,
    BillingOpsSnapshotView,
    BillingPlatformAuditFeedView,
    BillingPlatformMonitoringView,
    BillingPlatformSubscriptionsView,
    BillingPlatformOpsSummaryView,
    BillingPlatformRevenueView,
    BillingPlatformWebhookBulkReprocessView,
    BillingPlatformWebhookEventsView,
    BillingPlatformWebhookReprocessView,
    BillingPlanCatalogView,
    BillingPublicPlanCatalogView,
    BillingReleaseGateView,
    BillingStatusView,
    BillingReconciliationRunView,
    BillingUpiCheckoutView,
    BillingUpiClaimView,
    BillingUpiConfirmView,
    BillingWebhookBulkReprocessView,
    BillingWebhookEventListView,
    BillingWebhookEventReprocessView,
    BillingWebhookSummaryView,
    RazorpayWebhookView,
)

urlpatterns = [
    path("billing/status", BillingStatusView.as_view(), name="billing-status"),
    path("billing/plans", BillingPlanCatalogView.as_view(), name="billing-plan-catalog"),
    path("billing/public-plans", BillingPublicPlanCatalogView.as_view(), name="billing-public-plan-catalog"),
    path("billing/go-live-check", BillingGoLiveCheckView.as_view(), name="billing-go-live-check"),
    path("billing/observability", BillingObservabilityView.as_view(), name="billing-observability"),
    path("billing/ops-snapshot", BillingOpsSnapshotView.as_view(), name="billing-ops-snapshot"),
    path("billing/ops-digest", BillingOpsDigestView.as_view(), name="billing-ops-digest"),
    path("billing/platform-ops-summary", BillingPlatformOpsSummaryView.as_view(), name="billing-platform-ops-summary"),
    path("billing/platform-subscriptions", BillingPlatformSubscriptionsView.as_view(), name="billing-platform-subscriptions"),
    path(
        "billing/platform-revenue",
        BillingPlatformRevenueView.as_view(),
        name="billing-platform-revenue",
    ),
    path("billing/platform-monitoring", BillingPlatformMonitoringView.as_view(), name="billing-platform-monitoring"),
    path(
        "billing/platform-webhook-events",
        BillingPlatformWebhookEventsView.as_view(),
        name="billing-platform-webhook-events",
    ),
    path(
        "billing/platform-webhook-events/<uuid:event_id>/reprocess",
        BillingPlatformWebhookReprocessView.as_view(),
        name="billing-platform-webhook-reprocess",
    ),
    path(
        "billing/platform-webhook-events/reprocess-bulk",
        BillingPlatformWebhookBulkReprocessView.as_view(),
        name="billing-platform-webhook-bulk-reprocess",
    ),
    path("billing/platform-audit-feed", BillingPlatformAuditFeedView.as_view(), name="billing-platform-audit-feed"),
    path("billing/release-gate", BillingReleaseGateView.as_view(), name="billing-release-gate"),
    path(
        "billing/reconciliation/run",
        BillingReconciliationRunView.as_view(),
        name="billing-reconciliation-run",
    ),
    path("billing/checkout", BillingCheckoutView.as_view(), name="billing-checkout"),
    path("billing/checkout/upi", BillingUpiCheckoutView.as_view(), name="billing-upi-checkout"),
    path(
        "billing/checkout/upi/<uuid:session_id>/claim",
        BillingUpiClaimView.as_view(),
        name="billing-upi-claim",
    ),
    path(
        "billing/checkout/upi/<uuid:session_id>/confirm",
        BillingUpiConfirmView.as_view(),
        name="billing-upi-confirm",
    ),
    path("billing/webhooks/summary", BillingWebhookSummaryView.as_view(), name="billing-webhook-summary"),
    path(
        "billing/webhooks/reprocess-bulk",
        BillingWebhookBulkReprocessView.as_view(),
        name="billing-webhook-bulk-reprocess",
    ),
    path("billing/webhooks/events", BillingWebhookEventListView.as_view(), name="billing-webhook-events"),
    path(
        "billing/webhooks/events/<uuid:event_id>/reprocess",
        BillingWebhookEventReprocessView.as_view(),
        name="billing-webhook-reprocess",
    ),
    path(
        "billing/webhooks/razorpay",
        RazorpayWebhookView.as_view(),
        name="billing-razorpay-webhook",
    ),
]
