# Generated by Django 5.2.15 on 2026-07-04 19:14

import django.db.models.deletion
from django.db import migrations, models

import apps.businesses.validators.businesses
import apps.core.db.uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0003_rename_tenants_slug_f70d36_idx_tenants_slug_899f50_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_code", models.SlugField(max_length=80)),
                ("business_name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("business_type", models.CharField(blank=True, max_length=120)),
                ("industry_category", models.CharField(blank=True, db_index=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("logo", models.URLField(blank=True)),
                ("banner_image", models.URLField(blank=True)),
                ("primary_contact", models.CharField(blank=True, max_length=32)),
                ("secondary_contact", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(blank=True, db_index=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=120)),
                ("city", models.CharField(blank=True, db_index=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=32)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[apps.businesses.validators.businesses.validate_latitude],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[apps.businesses.validators.businesses.validate_longitude],
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("language", models.CharField(default="en", max_length=16)),
                ("gst_tax_number", models.CharField(blank=True, max_length=80)),
                ("registration_number", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_verification", "Pending Verification"),
                            ("verified", "Verified"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.businesses.validators.businesses.validate_tags],
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="businesses",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "businesses",
                "ordering": ["display_name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BusinessMedia",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("logo", "Logo"),
                            ("banner", "Banner"),
                            ("gallery_image", "Gallery Image"),
                            ("document", "Document"),
                            ("certificate", "Certificate"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=160)),
                ("file_url", models.URLField()),
                ("storage_backend", models.CharField(default="url", max_length=80)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "business_media",
                "ordering": ["sort_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mission", models.TextField(blank=True)),
                ("vision", models.TextField(blank=True)),
                ("about", models.TextField(blank=True)),
                ("working_days", models.JSONField(blank=True, default=list)),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("break_hours", models.JSONField(blank=True, default=list)),
                ("emergency_contact", models.CharField(blank=True, max_length=32)),
                ("booking_lead_time", models.PositiveIntegerField(default=0)),
                ("booking_window", models.PositiveIntegerField(default=30)),
                ("cancellation_policy", models.TextField(blank=True)),
                ("rescheduling_policy", models.TextField(blank=True)),
                ("social_media_links", models.JSONField(blank=True, default=dict)),
                ("seo_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "business_profiles",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_settings", models.JSONField(blank=True, default=dict)),
                ("appointment_duration_defaults", models.JSONField(blank=True, default=dict)),
                ("buffer_time", models.PositiveIntegerField(default=0)),
                ("business_hours", models.JSONField(blank=True, default=dict)),
                ("holiday_handling", models.JSONField(blank=True, default=dict)),
                ("time_slot_interval", models.PositiveIntegerField(default=15)),
                ("notification_preferences", models.JSONField(blank=True, default=dict)),
                ("invoice_preferences", models.JSONField(blank=True, default=dict)),
                ("localization", models.JSONField(blank=True, default=dict)),
                ("theme_overrides", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "business_settings",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="businesses_is_acti_231063_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(fields=["created_at"], name="businesses_created_bb3563_idx"),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(fields=["updated_at"], name="businesses_updated_c1e14b_idx"),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="businesses_tenant__0bfed1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["tenant", "created_at"], name="businesses_tenant__a30a99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["tenant", "business_code"], name="businesses_tenant__26ac2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["tenant", "status", "verification_status"],
                name="businesses_tenant__670f2b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["tenant", "industry_category", "city"], name="businesses_tenant__bea0c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["tenant", "country", "city"], name="businesses_tenant__2cbe6e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="business",
            constraint=models.UniqueConstraint(
                fields=("tenant", "business_code"), name="uq_business_tenant_code"
            ),
        ),
        migrations.AddIndex(
            model_name="businessmedia",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="business_me_is_acti_22cf34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessmedia",
            index=models.Index(fields=["created_at"], name="business_me_created_168bbe_idx"),
        ),
        migrations.AddIndex(
            model_name="businessmedia",
            index=models.Index(fields=["updated_at"], name="business_me_updated_d26df7_idx"),
        ),
        migrations.AddIndex(
            model_name="businessmedia",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="business_me_tenant__3b9e6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessmedia",
            index=models.Index(
                fields=["tenant", "created_at"], name="business_me_tenant__5b2c6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessmedia",
            index=models.Index(
                fields=["tenant", "business", "media_type"], name="business_me_tenant__ed72a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessprofile",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="business_pr_is_acti_0de9bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessprofile",
            index=models.Index(fields=["created_at"], name="business_pr_created_8de76d_idx"),
        ),
        migrations.AddIndex(
            model_name="businessprofile",
            index=models.Index(fields=["updated_at"], name="business_pr_updated_80c8d5_idx"),
        ),
        migrations.AddIndex(
            model_name="businessprofile",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="business_pr_tenant__e9a44b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessprofile",
            index=models.Index(
                fields=["tenant", "created_at"], name="business_pr_tenant__6f78f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businesssettings",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="business_se_is_acti_54da58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businesssettings",
            index=models.Index(fields=["created_at"], name="business_se_created_114d3c_idx"),
        ),
        migrations.AddIndex(
            model_name="businesssettings",
            index=models.Index(fields=["updated_at"], name="business_se_updated_b9e125_idx"),
        ),
        migrations.AddIndex(
            model_name="businesssettings",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="business_se_tenant__5b6f98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businesssettings",
            index=models.Index(
                fields=["tenant", "created_at"], name="business_se_tenant__1576c7_idx"
            ),
        ),
    ]
