# Generated by Django 5.2.15 on 2026-07-07 10:30

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

import apps.core.db.uuid


def backfill_product_subscriptions(apps, schema_editor):
    Business = apps.get_model("businesses", "Business")
    BusinessProductSubscription = apps.get_model("businesses", "BusinessProductSubscription")

    for business in Business.objects.exclude(selected_product="").exclude(selected_product__isnull=True):
        BusinessProductSubscription.objects.get_or_create(
            tenant_id=business.tenant_id,
            business_id=business.id,
            product_code=business.selected_product,
            defaults={
                "status": "trialing",
                "subscribed_at": timezone.now(),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_add_selected_product_to_business"),
        ("tenancy", "0003_rename_tenants_slug_f70d36_idx_tenants_slug_899f50_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessProductSubscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_code", models.CharField(db_index=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="trialing",
                        max_length=32,
                    ),
                ),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_subscriptions",
                        to="businesses.business",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "business_product_subscriptions",
                "ordering": ["subscribed_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="businessproductsubscription",
            index=models.Index(fields=["tenant", "is_active"], name="business_pr_tenant__8f0f0a_idx"),
        ),
        migrations.AddIndex(
            model_name="businessproductsubscription",
            index=models.Index(fields=["business", "product_code"], name="business_pr_busines_0c8f1d_idx"),
        ),
        migrations.AddIndex(
            model_name="businessproductsubscription",
            index=models.Index(fields=["business", "status"], name="business_pr_busines_6a2b9e_idx"),
        ),
        migrations.AddConstraint(
            model_name="businessproductsubscription",
            constraint=models.UniqueConstraint(
                fields=("business", "product_code"),
                name="uq_business_product_subscription",
            ),
        ),
        migrations.RunPython(backfill_product_subscriptions, migrations.RunPython.noop),
    ]
