# Generated by Django 5.2.15 on 2026-07-07 10:45

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def backfill_subscription_plans(apps, schema_editor):
    BusinessProductSubscription = apps.get_model("businesses", "BusinessProductSubscription")
    SubscriptionPlan = apps.get_model("tenancy", "SubscriptionPlan")

    default_plan_codes = {
        "appointie": "appointie-starter",
        "invoiceie": "invoiceie-starter",
        "crmie": "crmie-starter",
    }
    default_plan_names = {
        "appointie-starter": "AppointIE Starter",
        "invoiceie-starter": "InvoiceIE Starter",
        "crmie-starter": "CRMIE Starter",
    }

    now = timezone.now()
    for subscription in BusinessProductSubscription.objects.all():
        plan_code = default_plan_codes.get(subscription.product_code, subscription.product_code)
        plan, _ = SubscriptionPlan.objects.get_or_create(
            code=plan_code,
            defaults={
                "name": default_plan_names.get(plan_code, plan_code.replace("-", " ").title()),
                "is_public": True,
            },
        )
        subscription.plan_id = plan.id
        subscription.billing_interval = "monthly"
        if not subscription.trial_ends_at:
            subscription.trial_ends_at = now
        if not subscription.current_period_starts_at:
            subscription.current_period_starts_at = subscription.subscribed_at or now
        if not subscription.current_period_ends_at:
            subscription.current_period_ends_at = (subscription.subscribed_at or now) + timezone.timedelta(days=30)
        subscription.save(
            update_fields=[
                "plan_id",
                "billing_interval",
                "trial_ends_at",
                "current_period_starts_at",
                "current_period_ends_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0003_business_product_subscriptions"),
        ("tenancy", "0003_rename_tenants_slug_f70d36_idx_tenants_slug_899f50_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessproductsubscription",
            name="billing_interval",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                default="monthly",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="businessproductsubscription",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessproductsubscription",
            name="current_period_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessproductsubscription",
            name="current_period_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessproductsubscription",
            name="external_billing_reference",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name="businessproductsubscription",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_product_subscriptions",
                to="tenancy.subscriptionplan",
            ),
        ),
        migrations.RunPython(backfill_subscription_plans, migrations.RunPython.noop),
    ]
