# Generated by Django 5.2.15 on 2026-07-07 07:11

import apps.core.db.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0005_branch_and_dashboard_preferences"),
        ("tenancy", "0003_rename_tenants_slug_f70d36_idx_tenants_slug_899f50_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="businessproductsubscription",
            name="business_pr_tenant__8f0f0a_idx",
        ),
        migrations.RenameIndex(
            model_name="branch",
            new_name="branches_tenant__93ca91_idx",
            old_name="branches_tenant_business_status_idx",
        ),
        migrations.RenameIndex(
            model_name="branch",
            new_name="branches_tenant__36b6e5_idx",
            old_name="branches_tenant_business_primary_idx",
        ),
        migrations.RenameIndex(
            model_name="businessproductsubscription",
            new_name="business_pr_busines_8a3bbd_idx",
            old_name="business_pr_busines_0c8f1d_idx",
        ),
        migrations.RenameIndex(
            model_name="businessproductsubscription",
            new_name="business_pr_busines_78e725_idx",
            old_name="business_pr_busines_6a2b9e_idx",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="created_by_id",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="deleted_by_id",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="updated_by_id",
        ),
        migrations.AddField(
            model_name="branch",
            name="created_by",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="deleted_by",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="updated_by",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="id",
            field=models.UUIDField(
                default=apps.core.db.uuid.generate_uuid,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="businessproductsubscription",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="branches_is_acti_41e3cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(fields=["created_at"], name="branches_created_65bfb9_idx"),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(fields=["updated_at"], name="branches_updated_95199a_idx"),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="branches_tenant__cf795b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(fields=["tenant", "created_at"], name="branches_tenant__b295cc_idx"),
        ),
        migrations.AddIndex(
            model_name="businessproductsubscription",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="business_pr_is_acti_3b20a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessproductsubscription",
            index=models.Index(fields=["created_at"], name="business_pr_created_75069e_idx"),
        ),
        migrations.AddIndex(
            model_name="businessproductsubscription",
            index=models.Index(fields=["updated_at"], name="business_pr_updated_786079_idx"),
        ),
        migrations.AddIndex(
            model_name="businessproductsubscription",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="business_pr_tenant__6b8d99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessproductsubscription",
            index=models.Index(
                fields=["tenant", "created_at"], name="business_pr_tenant__1c3842_idx"
            ),
        ),
    ]
