# Generated by Django 5.2.15 on 2026-07-07 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0007_whitelabelprofile"),
        ("tenancy", "0003_rename_tenants_slug_f70d36_idx_tenants_slug_899f50_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="whitelabelprofile",
            options={},
        ),
        migrations.RenameIndex(
            model_name="whitelabelprofile",
            new_name="white_label_tenant__604003_idx",
            old_name="white_label_tenant__a1f2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="whitelabelprofile",
            new_name="white_label_tenant__970f62_idx",
            old_name="white_label_tenant__b4d5e6_idx",
        ),
        migrations.AlterField(
            model_name="whitelabelprofile",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="whitelabelprofile",
            index=models.Index(
                fields=["is_active", "deleted_at"], name="white_label_is_acti_c1270a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whitelabelprofile",
            index=models.Index(fields=["created_at"], name="white_label_created_f4200f_idx"),
        ),
        migrations.AddIndex(
            model_name="whitelabelprofile",
            index=models.Index(fields=["updated_at"], name="white_label_updated_4bb09d_idx"),
        ),
        migrations.AddIndex(
            model_name="whitelabelprofile",
            index=models.Index(
                fields=["tenant", "is_active", "deleted_at"], name="white_label_tenant__962f8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whitelabelprofile",
            index=models.Index(
                fields=["tenant", "created_at"], name="white_label_tenant__9f2ccb_idx"
            ),
        ),
    ]
