# Generated by Django 5.2.16 on 2026-07-26 07:19

import apps.businesses.validators.businesses
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0009_expand_asset_url_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[apps.businesses.validators.businesses.validate_latitude],
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[apps.businesses.validators.businesses.validate_longitude],
            ),
        ),
        migrations.AddField(
            model_name="businessproductsubscription",
            name="extra_offices",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="businessproductsubscription",
            name="extra_staff",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="businessproductsubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("trialing", "Trialing"),
                    ("active", "Active"),
                    ("soft_locked", "Soft Locked"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="trialing",
                max_length=32,
            ),
        ),
    ]
