# Generated by Django 5.2.16 on 2026-07-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0011_subscription_period_lock"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="businessproductsubscription",
            new_name="business_pr_current_1ace14_idx",
            old_name="business_pr_current_7d2f1a_idx",
        ),
    ]
